### ISSUE TITLE
Supply known entity data to `preflight`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1003]
## What

As a manager, I could really do with knowing any data about a new entity up-front in `preflight`, rather than just its trait set.

## Why

Take the scenario of generating a render bundle automatically from a single user/pipeline supplied anchor entity ref (the logical render bundle), the host flow is this (in horrible, unrealistic, unoptimised code):

```python
# Preflight the whole bundle
render_bundle.working_ref = manager.preflight(render_bundle.ref, RenderBundleSpecification.kTraitSet)
# Render each layer
for layer in render_layers:
   # Preflight the layer
   layer.working_ref = manager.preflight(render_bundle.working_ref, RenderLayer.kTraitSet)
   # Render its AOVs and register them
   for aov in layer.aovs:
      aov.working_ref = manager.preflight(layer.working_ref, RenderLayerAOV.kTraitSet)
      aov.render_location = manager.resolve(aov.working_ref, {LocatableContentTrait.kId}) 
      do_render(aov)
      manager.register(aov.working_ref, aov.toTraitsData())
  # Now the layer AOVs are done, register the layer to mark the end of AOVs
  manager.register(layer.working_ref, layer.toTraitsData())
# Now the layers are done register the bundle to show we're done.
manager.register(render_bundle.working_ref, render_bundle.toTraitsData())
```

The layer, and bundle name is in `Named` trait in the `TraitsData` passed to `register`, but I don't get this till _after_ all the work is done. If I wanted the `resolve` for each AOV to form a path such as `/project/.../<render_bundle>/<layer>/<aov>.####.exr` then I'm stuck as I don't know the layer or AOV name untill too late! It also means that there is no way to use any data in the formulation of the placeholder entity (eg, it's name etc).

This forces me to generate some suitably unique temporary path and placeholder references, then re-shuffle things later! Some may be OK with this, but it is creating a _lot_ of extra work, and precludes many in-place workflows.

## ACs

 - A manager is able to leverage known trait data for each entity in `preflight` in it's implementation.

**Comment by foundrytom** [comment]
## Proposal

Change the `traitSet` parameter of the `preflight` method to be an array of `TraitsData` objects, corresponding exactly with those subsequently passed to `register`. This would perform the same validation as `register` to guard against mis-matched trait sets.

### Before

```C++
virtual void preflight(const EntityReferences&, const trait::TraitSet&, ...);
virtual void register_(const EntityReferences&, const trait::TraitsDatas&, ...);
```

### After

 ```C++
virtual void preflight(const EntityReferences&, const trait::TraitsDatas&, ...);
virtual void register_(const EntityReferences&, const trait::TraitsDatas&, ...);
```

## Example

The above example would then become:

```python
# Preflight the whole bundle
render_bundle.working_ref = manager.preflight(render_bundle.ref, render_bundle.toTraitsData())
# Render each layer
for layer in render_layers:
   # Preflight the layer
   layer.working_ref = manager.preflight(layer.ref, layer.toTraitsData())
   # Render its AOVs and register them
   for aov in layer.aovs:
      aov.working_ref = manager.preflight(layer.working_ref, aov.toTraitsData())
      aov.render_location = manager.resolve(aov.working_ref, {LocatableContentTrait.kId}) 
      do_render(aov)
      manager.register(aov.working_ref, aov.toTraitsData())
  # Now the layer AOVs are done, register the layer to mark the end of AOVs
  manager.register(layer.working_ref, layer.toTraitsData())
# Now the layers are done register the bundle to show we're done.
manager.register(render_bundle.working_ref, render_bundle.toTraitsData())
```

**Comment by feltech** [comment]
# Proposal 2 :grin: 

`register` available (incomplete) information as soon as possible using a `kTransient` context hint.

# Example

```python
# Preflight the whole bundle
render_bundle.working_ref = manager.preflight(render_bundle.ref, RenderBundleSpecification.kTraitSet)
# Render each layer
for layer in render_layers:
   # Preflight the layer
   layer.working_ref = manager.preflight(layer.ref, RenderLayer.kTraitSet)
   # Render its AOVs and register them
   for aov in layer.aovs:
      aov.working_ref = manager.preflight(layer.working_ref, RenderLayerAOV.kTraitSet)

      # `register` the data we already know about
      transient_context = manager.createChildContext(context)
      transient_context.retention = kTransient
      aov.transient_ref = manager.register(aov.working_ref, aov.toTraitsData(), transient_context)
      # `preflight` the newly created, partially complete, entity
      aov.working_ref = manager.preflight(aov.transient_ref, RenderLayerAOV.kTraitSet)

      aov.render_location = manager.resolve(aov.working_ref, {LocatableContentTrait.kId}) 
      do_render(aov)
      manager.register(aov.working_ref, aov.toTraitsData())
  # Now the layer AOVs are done, register the layer to mark the end of AOVs
  manager.register(layer.working_ref, layer.toTraitsData())
# Now the layers are done register the bundle to show we're done.
manager.register(render_bundle.working_ref, render_bundle.toTraitsData())
```

# Pros and Cons

## Pros

* No API changes necessary.
* The manager can use metadata provided up-front to influence any subsequent `preflight`/`resolve` behaviour.
* The manager only has to implement validation in a single method, `register`.
* A sequence of `preflight`/`register` pairs can inform the manager as discrete steps are completed in entity construction.

## Cons

* It's not clear how the manager should behave if metadata is _not_ `register`ed ahead of time - can it throw an error, or must it handle either case?
* Several additional lines of code for the host.
* Failure in a later `register` could leave incomplete entities in the system (though `kTransient` retention helps).

**Comment by foundrytom** [comment]
Intersting idea!

> register available (incomplete) information as soon as possible using a kTransient context hint.
and
> A sequence of preflight/register pairs can inform the manager as discrete steps are completed in entity construction.

Is the intention that the manager throws away this information in the final register, which will provide all data in one, or that it is being slowly "assembled" through several register calls? 

`kTransient` passed to `register` is already defined as "I'm not able to keep the ref you give me" nothing will be retained, so perhaps a more first-class support though `access` or a new field would be beneficial? `kPartialWrite` or similar?

**Comment by foundrytom** [comment]
> The manager can use metadata provided up-front to influence any subsequent preflight/resolve behaviour.

Does it still leave the initial preflight being stuck with always having to generate a temporary reference?

**Comment by feltech** [comment]
Thinking about it though, this is a severe weakness of the multiple-`register` approach, and to a lesser extent the `TraitsData` in `preflight` approach.  

I.e. how can the host know if the manager requires some data to be `register`ed (or `preflight`ed) ahead of the final `register`?  

We can say that it's defined in the Trait/Specification, but is that reasonable?  Some managers could support `/tmp` workflows whereas others want data placed in the final location immediately.  How is that communicated to the host?

**Comment by foundrytom** [comment]
Affected as part of #1028
