### ISSUE TITLE
Investigate Python binding by-reference of value types

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1004]
## What

Check/fix our non-`shared_ptr` held types to ensure that pybind11 reference semantics aren't going to cause any problems.

## Why

pybind11 will pass types by reference, rather than copying, if it can.  E.g. `EntityReference` objects created in Python, then passed through C++ (as a const ref) and back out to Python, references the same object throughout.  

If an object is held in a list, and the list is passed between C++ and Python, then the object is copied along with the list, since pybind11 auto-conversion of `std::vector` to Python `list` requires a copy.  This presents an inconsistency between single objects vs. lists of objects.

A particularly dangerous scenario is if a C++ temporary object is created and passed as a const ref to a Python function (via a pybind11 trampoline), whereupon the Python script could hold on to a (non-const) reference to that temporary.  We should figure out what guarantees pybind11 makes in this scenario and if we need to add any mitigation and coding standards.

**Comment by elliotcmorris** [comment]
We think if there was a danger here, it's a danger that would be caught by our tests. We're gonna trust Pybind11 to do the right thing here, along with our test coverage.
