### ISSUE TITLE
Auth related `BatchElementError` codes

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1009]
## What

Add an auth error code so that manager's have a means to inform the user that they do not have access to an asset.  We are thinking a generic auth error code, rather than a set of unauthorised/unauthenticated/permission denied error codes.

## Why

This is a precursor to having something more fleshed out, but just putting the error codes in gives managers and hosts an option in the meantime, and it's super simple.

## Acceptance Criteria

Add a new error code `kAuthError`

**Comment by elliotcmorris** [comment]
What!?

**Comment by elliotcmorris** [comment]
Think about this, could be a source level data break for non exhaustive switches.
