### ISSUE TITLE
EntityExists has surprising list semantics

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1023]
## What
Came up when working on a browser.

https://github.com/elliotcmorris/OpenAssetIO/blob/c3063786d93579e9da9c77ab9d27b65ae32e450b/src/openassetio-python/package/openassetio/hostApi/Manager.py#L145

`EntityExists` has a surprising interface without reading the doc. It would more appropriately be called `EntitiesExist`
## Why
Workflows with singular entity references are common, we know this as we have implemented singular conveniences for other methods.
It is natural to write 
```python
if manager.EntityExists(my_entity_ref):
```
which is invalid. A name change would clear this up.
Furthermore though, once the implementor has deciphered the error message, they will likely do a head-slap, and then, being a lazy and falliable human, and especially as you find yourself using this pattern sometimes with other api methods, change their implementation to
```python
if manager.EntityExists([my_entity_ref]):
```
Which will make the error go away, but will somewhat hilariously, even if the return value is `[False]`, always return `True`, as that check is simply checking if the list is empty or not.

This is not a bug, nor even neccesarily a design issue, but I put forward the argument that this would be friendlier as an `EntitiesExist` method with an `EntityExists` singular convenience.

**Comment by foundrytom** [comment]
Have a look over https://github.com/OpenAssetIO/OpenAssetIO/blob/main/doc/decisions/DR003-ManagerInterface-method-naming.md - we had an awkward naming scenario here. We landed on keeping single names as ultimately _all_ entity related API methods are batch in some axis. However more recently, we no longer have methods such as `entityVersions`, or `entityName` so it's less obvious. This probably is the only non-verb method now.

**Comment by elliotcmorris** [comment]
This is clunky, but is a result of a wider decision to use singular terminology, even though this is on its own now, changing this would be a break for not much reason. Probably not going to do this without external feedback on it.
