### ISSUE TITLE
[Investigation] Consider extracting `Access` from `Context`

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1041]
## What

Consider removing `Access` from `Context`, making it a first class argument to methods that require it. 

## Why

`Access` (kWrite, kRead, kCreateRelated,) is a high velocity toggles which needs to be changed in pretty much every workflow. Having to go through `Context` is odd, and means you have to remember to set Access correctly. Furthermore, it creates confusion like "if i'm changing the access, do I need to user `createChildContext`?. 

## ACs

- Sketch out the new signatures for affected methods that consider usability and implementability.
- Matrix of which methods use which access.

**Comment by elliotcmorris** [comment]
Sketches of approaches. Output of discussion between myself and @feltech 

In the name of rapidity, we dismissed several approaches without sketching due to their obvious scope.

The only methods that have signature implications are in `Manager/ManagerInterface`
Below is a list of these methods, along with which Access modes we feel are relevant/allowed for them.
- `managementPolicy` - All
- `entityExists` - Read/Write
- `resolve` - Read/Write
- `getWithRelationship(s)(paged)` - Read/CreateRelated
- `preflight `- Write/CreateRelated
- `register` - Write/CreateRelated

The following sketches arbitrarily pick `preflight` as the example, but the patterns remain the same.

## Do nothing
#### Advantages:
  - No work
#### Disadvantages
  - Folks forget to set Access
  - Unclear if serialization of state token includes access

## Add extracted access argument to sigs.
#### Advantages :
  - Direct and non-risky, changes very little conceptually
  - Can't just use default anymore, have to think about it.
#### Disadvantages :
  - Adds another argument to already long sigs.

```cpp
// Add access arg
std::vector<std::variant<BatchElementError, EntityReference>>
preflight(const EntityReferences &entityReferences,
          const trait::TraitsDatas &traitsHints, const ContextConstPtr &context,
          Access access,
          const BatchElementErrorPolicyTag::Variant &errorPolicyTag);

```
## Method specific enum
#### Advantages :
 - Limits access type to only valid access types
 - Allows for individual functions to have unique specific access types if neccesary
 - Good documentation
 - Can't just use default anymore, have to think about it.
#### Disadvantages :
 - Adds another argument to already long sigs.
 - We have to decide now in a strict manner what access modes each method supports.
 - Some additional file bloat.
```cpp

// Enums declared with set values to allow casting between them.
enum class WriteOrReadAccess : unsigned int {
  Read = 0,
  Write = 1
};
enum class WriteOrCreateRelatedAccess : unsigned int {
  Write = 1,
  CreateRelated = 2
};

using PreflightAccess = WriteOrCreateRelatedAccess;
std::vector<std::variant<BatchElementError, EntityReference>>
preflight(const EntityReferences &entityReferences,
          const trait::TraitsDatas &traitsHints, const ContextConstPtr &context,
          PreflightAccess access,
          const BatchElementErrorPolicyTag::Variant &errorPolicyTag);
```
Note : There's an argument not to alias PreflightAccess and instead
declare each one, to stop accidental reuse between methods. Although
this increases verbosity.

## Encode access in the entity reference
#### Advantages :
  - Manager can dictate appropriate access
  - Appropriate access is made directly available to the host
  - In the simple case, no API changes required

#### Disadvantages :
  - Large implications around re-examining the api. For this reason,
    even though this _might_ be the best change, we are rejecting it
    due to scope.
  - Dosen't solve the hidden-access thing, as we just move it from one
    object to another.

## Individual methods/tag dispatching
- Rejected outright due to the combinatorial explosion of conveniences.

**Comment by foundrytom** [comment]
@elliotcmorris 
> entityExists - Read/Write

`entityExists` isn't meant to be sensitive to access.

**Comment by foundrytom** [comment]
Great writeup, thanks. Did you folks give any thought to the relative order of the parameters? Especially for ones where the access is quite critical in defining behaviour (eg resolve)

**Comment by foundrytom** [comment]
Closing as we now have #1054
