### ISSUE TITLE
Add stringification for `BatchElementError`

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1049]
## What

Add a function to convert a `BatchElementError` to a string, exposed as `__repr__` (and perhaps  `__str__`) in the Python bindings.

## Why

It is useful for debug output to be able to print a `BatchElementError` without having to print its members independently.

E.g. when a test fails an equality check in Python, the output is similar to the following rather useless message, which actually implies a difference in memory address rather than contents:

```
AssertionError: Lists differ: [<openassetio._openassetio.BatchElementError object at 0x7feed34f78b0>] != [<openassetio._openassetio.BatchElementError object at 0x7feed37761f0>]

First differing element 0:
<openassetio._openassetio.BatchElementError object at 0x7feed34f78b0>
<openassetio._openassetio.BatchElementError object at 0x7feed37761f0>

- [<openassetio._openassetio.BatchElementError object at 0x7feed34f78b0>]
?                                                                ^ ---

+ [<openassetio._openassetio.BatchElementError object at 0x7feed37761f0>]
?                                                                ^^^^
```

**Comment by foundrytom** [comment]
YES PLEASE!!!!
