### ISSUE TITLE
Remove `access` from `Context`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1054]
## What

👆

## Why

https://github.com/OpenAssetIO/OpenAssetIO/blob/main/doc/decisions/DR019-Remove-access-from-the-context.md

## Acceptance Criteria

- `access` removed from `Context`
- New specific enums added to the `openassetio::access` namespace for specific workflows:
  - **`PolicyAccess` (`managementPolicy`)**: `kRead`, `kWrite`, `kCreateRelated`
  - **`RelationsAccess` (`getWithRelationship*`)**: `kRead`, `kWrite`, `kCreateRelated`
  - **`ResolveAccess` (`resolve`)**: `kRead`, `kWrite`
  - **`PublishingAccess` (`preflight`/`register`)**: `kWrite`, `kCreateRelated`
  - Matching enum members should have the same value across the definitions.
  - `kAccessNames` array persisted to allow bi-directional string conversions.
 - Methods update with the above as a[nother] positional argument `access` at the end of the batch arguments, before `context` or `hostSession`, callbacks.
 - Validate existing docs that refer to `access` are still meaningful, no additional docs required.
 - `Examples.dox` updated
 - `simpleResolver` updated
 - Significant note in `RELEASE_NOTES` via block quote with `**Warning:**` heading.
- Python bindings hoist contents of `access` in python `access/__init__.py` to allow `from openassetio.access import ResolveAccess`

**Comment by feltech** [comment]
Re. access/__init__.py` - the pattern followed for other single-module namespaces is to use a module for the namespace, e.g. `log.py` covers the `log` namespace.  So for consistency we should create an `access.py`.

**Comment by feltech** [comment]
For posterity, based on offline conversation to eliminate ambiguity:

> Methods update with the above as a[nother] positional argument access at the end of the batch arguments, before context or hostSession, callbacks.

would perhaps be better phrased as, "immediately to the left of `context`".

I.e. in-between "the end of the batch arguments" and "before context" there can be multiple other arguments.  We decided to keep the access argument alongside the context argument.
