### ISSUE TITLE
Remove objects.py

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1068]
## What
Delete [objects.py](https://github.com/OpenAssetIO/OpenAssetIO/blob/main/src/openassetio-python/package/openassetio/_core/objects.py)
## Why
Does anybody know what it does? It's types don't seem to be referenced outside of itself.

**Comment by foundrytom** [comment]
BIN IT!!!!!!! Its from a bygone age.
