### ISSUE TITLE
Update `BatchElementException` hierarchy

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1073]
## What

Update the `BatchElementException` hierarchy to include additional useful information for hosts, including an intermediate base class allowing entity reference -specific errors to be filtered.

## Why

The current `BatchElementException`s currently include the element index as a data member, but simply regurgitate the underlying `BatchElementError` message. Given the location where the exception is caught could be far from the call site, additional information in the error object and message would be valuable to the host.

## ACs

* All `BatchElementError` and `BatchElementException` types moved under an `errors` namespace.
* ~~Aliases added in place of previous location, with `[[deprecated]]` annotation (and equivalent for Python, if possible).~~ Decided to allow breaking changes based on [TSC]()
* `BatchElementException` updated to inherit from (recently added) `OpenAssetIOException`
* All `BatchElementException` subclasses removed.
* `BatchElementException` constructor takes the index, the BEE and an optional `suffix` / `additionalIInfo` (or similar) string parameter.  
* The exception message:
  - should be all on one line, for nicer concurrency (flush-on-newline) and greppability
  - should begin with the `BatchElementError` type name (i.e. translate `code` to string)
  - if either the `BatchElementError.message` or `suffix` is provided, then follow with a `: `
  - then should include the `BatchElementError.message`, if non-blank 
  - then should include the suffix, if provided.
* `BatchElementException`-throwing methods updated to construct a `suffix` argument from available relevant information eg:
  - Entity reference as `[<entity reference>]`
  - Access mode as `[access=<mode>]`
  E.g. 
  - `"InvalidPreflightHint: manager-provided error [index=2][access=read][my://entity/ref]"`
  - `"EntityAccessError: [index=2][access=write][my://entity/ref]"`
  - `"Unknown: manager-specific error [index=2]"`
* `CODING_STANDARDS` updated with guidelines for the order of extra data
* log an issue for any future message enhancements

```[tasklist]
### Tasks
- [ ] Implement the feature
- [ ] Re-enable intregrations
```

**Comment by feltech** [comment]
A couple of changes to the original plan:

* All exception data members are `std::optional`, since we cannot prevent the manager from providing a `BatchElementError` with an inappropriate code for the API method.  We decided to go with a best-effort approach - filling in the details we have available.
* We decided against including the trait set/data in the error message, at least for now, to prevent unwieldy long messages or additional work figuring out appropriate truncation.

**Comment by foundrytom** [comment]
Playing devils advocate - if we're making them optional, and not using some of them in the message, is there any point putting them in at this juncture? YAGNI?

**Comment by feltech** [comment]
IIRC when we discussed it the argument was to provide users with all the information they could need, if not in the exception message then at least in the data structure.  I'd be happy to strip out everything that's not used for the exception message, though.

**Comment by foundrytom** [comment]
Totally up to you - just asking the annoying questions :)

**Comment by feltech** [comment]
ACs updated based on offline chat. For posterity:


## Abandoned ACs

The following ACs were abandoned due to the growing cost:value ratio of implementing and maintaining this structure.

* New intemediate base added
  ```c++
  struct BatchElementEntityReferenceException : BatchElementException {
    EntityReference entityReference;
  };
  ```
* `InvalidEntityReferenceBatchElementException` updated to inherit from `BatchElementEntityReferenceException` and suffix the wrapped `BatchElementError`'s message with a provided entity reference.
* `MalformedEntityReferenceBatchElementException` updated to inherit from `BatchElementEntityReferenceException` and suffix the wrapped `BatchElementError`'s message with a provided entity reference.
* `EntityAccessErrorBatchElementException` updated to inherit from `BatchElementEntityReferenceException` and suffix the wrapped `BatchElementError`'s message with a provided entity reference **and** stringified access modifier.
* `EntityResolutionErrorBatchElementException` updated to inherit from `BatchElementEntityReferenceException` and suffix the wrapped `BatchElementError`'s message with a provided entity reference.
* New exception type added
  ```c++
  struct InvalidTraitsDataBatchElementException : BatchElementException {
    std::optional<EntityReference> entityReference
    TraitsDataPtr traitsData;
  };
  ```
  - constructor suffixes the wrapped `BatchElementError`'s message with provided entity reference, if set, and the (truncated) `traitsData`.
* `InvalidPreflightHintBatchElementException` updated to inherit from `InvalidTraitsDataBatchElementException`
* `InvalitTraitSetBatchElementException` updated to
  ```c++
  struct InvalitTraitSetBatchElementException : BatchElementException {
    std::optional<EntityReference> entityReference
    TraitSet traitSet;
  };
  ```
  - constructor suffixes the wrapped `BatchElementError`'s message with provided entity reference, if set, and the `traitSet`
