### ISSUE TITLE
Deprecations/Polyfill/compatability strategy

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1083]
## What

Determine the strategy that will allow

- new manager plugins to be used in a14
- updated hosts using older plugins

**Comment by feltech** [comment]
Whatever solution we come up with, testing will no doubt be important. This could relate to #947, where we aim to create a set of workflow doctests. Executing old/new doctests in new/old versions of the API could be a cheap way to monitor compatibility.

**Comment by foundrytom** [comment]
TSC noted that theyd be happy with breaking changes in alpha releases.
