### ISSUE TITLE
CI job checking for ABI breaks

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1085]
## What

Add a CI job that ensures no unintentional ABI breaks and symbol leakage.

## Why

As we approach beta and v1 we need to ensure breaking changes are managed.  Part of that is ensuring no unintentional changes to the ABI. This was highlighted in recent work (https://github.com/OpenAssetIO/OpenAssetIO/issues/1070) where a new dependency was found to leak symbols. This particular case was spotted manually, but ideally our CI would flag such changes to the ABI.

Tools exist for this, e.g. https://github.com/lvc/abi-compliance-checker - as well as command-line tools like `nm` (must treat platforms independently though.

Could use a Docker container than can run locally, that's triggered by CI.

## Acceptance Criteria

- - Linux only
- Need to store either the dwarf symbol builds or abi symbol dumps for the most recent build

- If an MR breaks the ABI, the CI should raise the alarm

**Comment by elliotcmorris** [comment]
Our ABI protection namespace thingey depends on us getting this right. A tool would be much better than just having to know.

**Comment by feltech** [comment]
Another contender for an ABI checker is [libabigail](https://sourceware.org/libabigail/).  There's a comparison of ABI checker tools in a 2022 pre-print paper [Binary-level Software Compatibility Tool Agreement](https://arxiv.org/pdf/2212.03364). They land on libabigail as the most mature and well maintained and easiest to work with.

**Comment by feltech** [comment]
In my experiments with abi-compliance-checker, it would not flag the re-ordering of two private members as an ABI break [even though it is](https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B).

Similarly, libabigail's `abidiff` tool does not flag this change - until I added the `--non-reachable-types` command line argument, and voila (and also causes symbols to be demangled, for some reason).

Using `ghcr.io/buildsi/libabigail` Docker image with two builds of OpenAssetIO, one original (`prev`), one updated
```sh
# abidiff --headers-dir1 /openassetio/prev/include/ --headers-dir2 /openassetio/include/ --fail-no-debug-info /openassetio/prev/lib/libopenassetio.so /openassetio/lib/libopenassetio.so

  [C] 'method openassetio::v1::pluginSystem::CppPluginSystem::CppPluginSystem(openassetio::v1::log::LoggerInterfacePtr)' at CppPluginSystem.cpp:103:1 has some indirect sub-type changes:
    implicit parameter 0 of type 'openassetio::v1::pluginSystem::CppPluginSystem* const' has sub-type changes:
      in unqualified underlying type 'openassetio::v1::pluginSystem::CppPluginSystem*':
        in pointed to type 'class openassetio::v1::pluginSystem::CppPluginSystem' at CppPluginSystem.hpp:34:1:
          type size hasn't changed
          2 data member changes:
            'openassetio::v1::log::LoggerInterfacePtr logger_' offset changed from 0 to 448 (in bits) (by +448 bits)
            'openassetio::v1::pluginSystem::CppPluginSystem::PluginMap plugins_' offset changed from 128 to 0 (in bits) (by -128 bits)
```

So that's a win for libabigail.

**Comment by feltech** [comment]
The need for `--non-reachable-types` seems to have gone by using a later version of libabigail (2.5.0 vs. 2.0.0)

**Comment by feltech** [comment]
libabigail's `abidiff` tool's exit status is a bitfield of flags. The [docs](https://sourceware.org/libabigail/manual/abidiff.html) for this reveal something about why some changes that seem like they should be ABI breaks are not flagged as important:

> Note that, at the moment, there are only a few kinds of ABI changes that would result in setting the flag ABIDIFF_ABI_INCOMPATIBLE_CHANGE. Those ABI changes are either:
>
> * the removal of the symbol of a function or variable that has been defined and exported.
> * the modification of the index of a member of a virtual function table (for C++ programs and libraries).
>
> With time, when more ABI change patterns are found to always constitute incompatible ABI changes, we will adapt the code to recognize those cases and set the ABIDIFF_ABI_INCOMPATIBLE_CHANGE accordingly.

**Comment by feltech** [comment]
It seems `abidiff` only uses headers (`--headers-dir-1` option in [docs](https://sourceware.org/libabigail/manual/abidiff.html)) to help filter ABI changes, and doesn't check ABI breaks in the headers themselves (i.e. template classes, inline functions)

>  The tool will thus filter out ABI changes on types that are not defined in public headers.

**Comment by feltech** [comment]
Came across a [google mirror](https://android.googlesource.com/platform/external/libabigail/) of libabigail, which says "Android no longer uses libabigail and has instead moved to STG". This is Google's own tool [Symbol-Type Graph](https://android.googlesource.com/platform/external/stg/), which seems to solve the same problem.  

Given I haven't seen much about STG elsewhere, and that it is "under active developement" and "arguments and behaviour are subject to change", and our integration of libabigail is nearly done and works well (though sometimes the output isn't very comprehensible), I don't propose to look into it further.  So just adding this comment for posterity.
