### ISSUE TITLE
Create `dist-info` with CMake built Python packages

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1088]
## What

Provide a skeleton `dist-info` along side the `openassetio` Python package in `dist`.

## Why

`openassetio` is an "interesting" dependency. It should generally be provide by the Host (as they're the ones initializing/using the API). However it is also a dependency of middleware like traits packages, and manager plugins.

In a simple, pure Python world, all components could list it as a dependency, and something like `pip` would install the right version, and flag any issues.

However, we are not in a simple pure Python world. Many hosts are C++, and so manage the dependency in a different way.

This poses a problem, as a C++ host, that provides a Python interpreter needs to single-source `openassetio` between C++ and Python using the dynamic library build (to avoid multiple copies of `openassetio` being loaded simultaneously, with potentially conflicting versions).

Presently, we don't provide a `dist-info` with our CMake build Python package. If we add a hard dependency on `openassetio` in a manager, when the manager is installed, the package manager can't see that `openassetio` is already satisfied, and instead installs its own (static linked) version, with out any regard to the version pin imposed by the host. This would mean that data objects returned by the manager may not be runtime compatible with the host.

Long-term, hosts may opt to use the C isolation layer, which would mitigate this issue (at the expense of a copy). We're not there yet, and so we need to ensure that an dependency check as part of a package install is able to 'see' the existing `openassetio` installation provided by a host with its embedded interpreter.

By providing a `dist-info` directory with our manual builds, it will allow package managers to determine if the fixed host provided package is compatible with the versioning requirements of the other packages being installed, and stop a second, potentially conflicting version being installed.

The same is true for MediaCreation.

## Acceptance Criteria

- CMake builds of the Python package include a `dist-info` directory with:
  - A minimal `METADATA` required by downstream tooling (or more if needed). 
  - An `INSTALLER` entry that lists `cmake`
  - No `RECORD` to [prevent other package managers from trying to uninstall it](https://packaging.python.org/en/latest/specifications/recording-installed-packages/#intentionally-preventing-changes-to-installed-packages) as part of a dependency upgrade.
  - A CMake option to disable `dist-info` generation.
- When this build is manually installed to a python interpreter, then`-m pip` installing a package with:
  - ... a compatible `openassetio` dependency, using that interpreter, sees the existing installation and considers the dependency satisfied.
  - ... an incompatible `openassetio` dependency errors, and does not attempt to uninstall/update the package
  - Tests that `pip`can see the package and version, and un-installation fails.

**Comment by feltech** [comment]
I did a `pip install openassetio` and took a look at the `openassetio-1.0.0a14.dist-info` directory.  There are a few metadata files in there, with docs saying what they are rather scattered around the web.  So some useful links

- [^1][^2] `METADATA`, `RECORD` and `INSTALLER`
- [^2] `REQUESTED`
- [^3] `top_level.txt`
- [^4] `WHEEL`

[^1] https://packaging.python.org/en/latest/specifications/recording-installed-packages
[^2] https://peps.python.org/pep-0376/
[^3] https://setuptools.pypa.io/en/latest/deprecated/python_eggs.html#top-level-txt-conflict-management-metadata
[^4] https://peps.python.org/pep-0427/
