### ISSUE TITLE
Deprioritise hoist links in doxygen output

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1093]
## What
In at least one view in the docs, only one class of the same name can be displayed. (Specifically i'm thinking of the `Namespace Members->All` page.)
A consequence of this is that when we have python hoists of the same name as the c++ types, it looks to be selecting the python hoist as the item to link to, rather than the useful c++ page.

This came up when doing errors, see screenshot : 
![image](https://github.com/OpenAssetIO/OpenAssetIO/assets/114349211/fc2b8a58-e750-475d-8cf7-1e7c5ea212e2)

There is no duplicate `BatchElementError` in the page that links to `v1`, that's the only reference.

We should find a way to prioritise linking the the c++ docs, perhaps by configuring doxygen to not scan the hoists.
## Why
The C++ should be our main docs in all views, linking to the hoists in unhelpful.

**Comment by foundrytom** [comment]
🤔 yeah it'd be good to hide those in general wouldn't it...
