### ISSUE TITLE
Path to URL utils

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1117]
## What

Provide helpers for path to URL and the reverse, available to Hosts and Managers

## Why

Traits generally use [URLs not paths](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/blob/main/decisions/DR001-Locatable-content-traits.md) (as we're dearly trying to get away from the filesystem being everything).

POSIX Path to URL can be relatively well defined, but Windows is another matter, and a hundred implementations of the same thing wont be. We need to provide a consistent implementation, that can also provide a consistent roundtrip-through-OpenAssetIO solution for windows, to avoid incompatibilities between hosts and managers.

## Acceptance Criteria

- High performance functions that provide path-to-URL (`file` scheme) and URL-to-path with roundtrip transparency. This code will be called in hot code paths so needs to have the minimum runtime overhead possible.
- Support for POSIX and Windows paths, including conversion on other platforms than the target. (As servers may well be running a different OS to the target they'r generating data for), default to system platform.
  - Windows needs to support standard paths, UNC paths, and Extended paths\UNC paths.
  - We need to be able to build/decode paths outside of the target host environment (e.g. windows in a linux runtime).
- The resulting URLs should be compatible with existing libraries that support [WHATWG `file` scheme URLs](https://url.spec.whatwg.org).
- Does not re-invent for well-solved problems (eg percent escape-sequence decoding).
- No public dependencies
- C++ implementation bound to Python
   - `enum class openassetio::utils::PathType { kSystem=0, kPOSIX, kWindows }`
   - `openassetio::Str openassetio::utils::pathToFileURL(openassetio::StrView absPath, PathType pathType)`
   - `openassetio::Str openassetio::utils::pathFromFileURL(openassetio::StrView fileURL, PathType pathType)`
- Exceptions thrown for invalid input including details of reason for failure, including.
  - Relative input paths
  - non-file URLs
  - URLs with hosts being convered to POSIX
  - Unicode input in paths is handled such that it works with other libraries that take `file` urls (ffmpeg is a good test bed).

## Notes

https://url.spec.whatwg.org
https://en.wikipedia.org/wiki/File_URI_scheme

It's worth learning about whether we want to suggest that URLs in openassetio (ie MC traits) should be normalized:

  https://www.unicode.org/reports/tr46/#ToASCII

If so, we need to make sure we convert back to UTF-8 when extracting the path from the URL.

### Transformations

POSIX

NB: We need to confirm the correct behaviour for Unicode [see here](https://learn.microsoft.com/en-us/archive/blogs/ie/file-uris-in-windows#non-us-ascii-characters), as we currently state URI not IRI.
```
file:///Testing/exr/cathedral/cathedral_withdisparity_%25V.%23%23%23%23.exr <-> /Testing/exr/cathedral/cathedral_withdisparity_%V.####.exr
file:///i%20/am/an%20awk%C3%A4d/%F0%9F%8E%83%20uni%C4%86%C3%B8%E2%88%82e/path <-> /i /am/an awkäd/🎃 uniĆø∂e/path
```

NB: The unicode behaviour above needs to be confirmed in relation to [the WHATWG URL standard] (https://www.unicode.org/reports/tr46/#ToASCII)
Windows Documented [here](https://learn.microsoft.com/en-us/archive/blogs/ie/file-uris-in-windows). 

### Managers populating `TraitsData` in `resolve` implementation

```python
asset_path = backend.get_path(entity, ...)
locatable_content_trait.setLocation(utils.pathToFileURL(asset_path))
```

### Hosts retrieving path from resolved data

```python
entity_data = manager.resolve(..., { LocatableContentTrait.kId}, ...)

if url := LocatableContentTrait(entity_data).getLocation()):
   path = utils.fileURLToPath(url)
```

**Comment by foundrytom** [comment]
Found this, may or may not be useful/appropriately licensed:

https://www.ada-url.com/

**Comment by elliotcmorris** [comment]
Thought this was interesting, a (seemingly) exhaustive procedure for windows file path identification https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#identify-the-path

**Comment by foundrytom** [comment]
Initial test skeleton that covers most of the above ACs:

  https://github.com/foundrytom/OpenAssetIO/commit/da0f24fa7c2490796685467217a7c086a20ff815

**Comment by themissingcow** [comment]
https://daniel.haxx.se/blog/2023/11/21/url-parser-performance/

**Comment by feltech** [comment]
According to https://metadataconsulting.blogspot.com/2019/04/Can-a-UNC-Network-Share-be-Unicode.html?m=1

> host-name must be a NetBIOS computer name according to
> https://support.microsoft.com/en-us/help/909264/naming-conventions-in-active-directory-for-computers-domains-sites-and
> however, the share-name can be Unicode. 

Ada [seems to conform](https://www.ada-url.com/playground?url=file%3A%2F%2Fh%F0%9F%98%84st%2Fpath%2Ft%F0%9F%98%84%2Ffile.exr) well

Input: `file://h😄st/path/t😄/file.exr`

Output: `file://xn--hst-7h33b/path/t%F0%9F%98%84/file.exr`

Another [reason to choose Ada](https://github.com/ada-url/ada/releases/tag/v1.0.0)

> It has been adopted by Node.js and will be part of future releases.

The [performance comparison](https://daniel.haxx.se/blog/2023/11/21/url-parser-performance/) that Tom found isn't particularly fond of Ada, but the alternatives, it mentions aren't particularly suitable: `libcurl` is a beast; and the extracted URL API `trurl` is a command-line tool with no docs.

**Comment by feltech** [comment]
According to [Microsoft UNC docs](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/62e862f4-2a51-452e-8eeb-dc4ff5ee33cc)

> The host-name string MUST be a NetBIOS name[...], a fully qualified domain name [...], an IPv4 address [...], or a [..] IPV6 address.

Then according to [Microsoft's Computer Name docs](https://learn.microsoft.com/en-us/windows/win32/sysinfo/computer-names)

> A computer is uniquely identified by its fully qualified DNS name

where the DNS name, interestingly

> are represented in the UTF-8 character set or Unicode. The name is not case sensitive.

and the NetBIOS name

> consist of up to 15 bytes of OEM characters including letters, digits, hyphens, and periods. Some characters are specific to the character set. NetBIOS names are typically represented in the OEM character set. The OEM character set depends on the locale. Some OEM character sets represent certain characters as two bytes. NetBIOS names, by convention, are represented in uppercase where the translation algorithm from lowercase to uppercase is OEM character set dependent.

implying it's also potentially unicode, depending entirely on locale.

I suspect the "Computer Name" spec may diverge from the URL/UNC spec, though...

**Comment by feltech** [comment]
Ada has support for idna conversion to and from ASCII encoded domain names.

It doesn't appear to have support for converting file URLs to paths all the way though, i.e. we'd have to handle Windows converting `/` to `\` and stripping leading `/` from drive letters.

**Comment by feltech** [comment]
A [StackOverflow post](https://stackoverflow.com/questions/2616011/easy-way-to-parse-a-url-in-c-cross-platform) with lots of library recommendations. 

I went through all of them (apart from the super-heavyweight libraries), and only one supports transforming `file://` URLs to/from paths: [uriparser](https://github.com/uriparser/uriparser)

It supports transforming Windows paths to/from URLs on Linux hosts, just like we want.  However, it has a 5 year old [open issue](https://github.com/uriparser/uriparser/issues/25) to support extended UNC paths (i.e. `\\?\` syntax).  The last merged PR was 2 months ago, so it's a reasonably alive project. BSD licensed. So perhaps a candidate to build on, and contribute fixes upstream?

**Comment by feltech** [comment]
Good summary of extended UNC from the [Windows docs](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces)

> For file I/O, the "\\?\" prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system. For example, if the file system supports large paths and file names, you can exceed the MAX_PATH limits that are otherwise enforced by the Windows APIs.

**Comment by feltech** [comment]
On Linux, Firefox strips the `server` from `file://server/path`.  `curl` gives an error if `server` is anything other than `localhost` (or blank).

**Comment by foundrytom** [comment]
> On Linux, Firefox strips the `server` from `file://server/path`. `curl` gives an error if `server` is anything other than `localhost` (or blank).

Think its worth updating the AC ("Exception for URLs with hosts being convered to POSIX") to allow `localhost`?

**Comment by feltech** [comment]
When developing test cases I wondered what characters must be percent encoded. 

The WHATWG specification [does specify](https://url.spec.whatwg.org/#percent-encoded-bytes), but it's tough to understand at a glance, given their style of writing like coding in English.

RFC 3986 [is a bit clearer](https://www.rfc-editor.org/rfc/rfc3986#section-2.2), but there's still some conditionality around when a particular character is reserved.

So it's not a simple case of "here's a list of reserved characters".  

Flipping the question, RFC 3986 does at least specify unconditionally _unreserved_ characters as `ALPHA / DIGIT / "-" / "." / "_" / "~"`.

**Comment by elliotcmorris** [comment]
> I went through all of them (apart from the super-heavyweight libraries), and only one supports transforming `file://` URLs to/from paths: [uriparser](https://github.com/uriparser/uriparser)

Huh, this is a great find, the lack of unicode is a big bummer, but if using this library reduces the problem to encoding / decoding unicode characters on either end that seems like a pretty big win to me? Could maybe use ICU for that?

**Comment by feltech** [comment]
Wish this was implemented right now: 

* https://github.com/ada-url/ada/issues/309

**Comment by feltech** [comment]
Source code links
* `swift-url`
  - [url from path](https://github.com/karwa/swift-url/blob/f9135f9f798af5ea9c2ab571ceaa128a03f69ea6/Sources/WebURL/WebURL%2BFilePaths.swift#L733)
  - [path from url](https://github.com/karwa/swift-url/blob/f9135f9f798af5ea9c2ab571ceaa128a03f69ea6/Sources/WebURL/WebURL%2BFilePaths.swift#L1029)
* .NET
  - [path from url](https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System/net/System/URI.cs#L1036)
  - url from path ...

**Comment by feltech** [comment]
I ended up using a regex library for the implementation. TLDR I chose [PCRE2](https://github.com/PCRE2Project/pcre2)

I went through a couple of benchmark lists as well as a list on Wikipedia
* https://github.com/HFTrader/regex-performance
* https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/
* https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines

I didn't do a deep dive, but picked a few libraries that were C or C++, maintained and well-regarded:

* [PCRE2](https://github.com/PCRE2Project/pcre2) is a battle-tested library used in e.g. Apache, PHP, Safari. "JIT" compiler brings performance near Hyperscan. C-only (C++ bindings are ancient and don't support JIT), though. ✔ 
* [Re2](https://github.com/google/re2) by Google is fast and C++. I has some reduced features for security reasons (untrusted input). This was the front-runner, but unfortunately brings in [abseil](https://github.com/abseil/abseil-cpp) as a dependency. ❌ 
* [Hyperscan](https://github.com/intel/hyperscan) by Intel  is by far the fastest, at least on benchmark data. However, no ARM support is a killer. Also dubious use of multithreading with no configurability. Designed for batch processing multiple regexes/documents at once. :x:
* [Boost.Regex](https://www.boost.org/doc/libs/1_84_0/libs/regex/doc/html/index.html) has good performance and a similar API to `std::regex`. However, it of course brings with it a dependency on boost, which we've so far avoided. :x:
* [ICU](https://icu.unicode.org/) is _the_ unicode library, but comes with a regex engine. Interesting due to giving us unicode support too. Hard to find benchmarks, but an [R benchmark](https://rpubs.com/jonclayden/regex-performance) implies its pretty good. A huge dependency though, and no official CMake support. :x:

**Comment by feltech** [comment]
During development I found a couple of issues with upstream libraries, posting here for posterity:

- https://github.com/karwa/swift-url/issues/182
- https://github.com/ada-url/ada/issues/580
