### ISSUE TITLE
Add cmake-lint

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1132]
## What

Add `cmake-lint` to build

## Why

Ensure a consistent style in CMake files. This is especially important as we start to attract outside collaborators.

## Notes

We have prior art in [TraitGen](https://github.com/OpenAssetIO/OpenAssetIO-TraitGen/blob/591863d593d21d988da2bcd8b8207467e7582d85/tests/generators/cpp/cmake/StaticAnalyzers.cmake#L90)

## Acceptance Criteria

- Determine applicability to other repos and log issues so we have consistent approach across projects (don't implement)
- `cmake-lint` enabled via a `cmake` option following the pattern of `cpplint` enabled in the `lint` preset.
- linter checks must match results of available formatting tools.

**Comment by foundrytom** [comment]
TODO: Understand the relationship with cmake-lint and cmake-format
