### ISSUE TITLE
Add markdownlint linter

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1137]
## What

Enforce a consistent style in CI (and when building?) for markdown files

## Why

It's quite easy to make typos and have inconsistent style with markdown files, affecting readability and reflecting professionalism.

E.g. https://github.com/OpenAssetIO/OpenAssetIO/pull/1135#discussion_r1343820944

**Comment by foundrytom** [comment]
Ideally this would be in build not just CI

**Comment by elliotcmorris** [comment]
Superceded by https://github.com/OpenAssetIO/OpenAssetIO/issues/774
