### ISSUE TITLE
Run `TraitGen` c++ tests in `integrations.yml`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1154]
## What

Run the c++ test suite as well as python in our integration tests.

## Why

We miss critical coverage of c++ changes.

## Acceptance Criteria

- TraitGen c++ tests are run as part of CI integration tests

**Comment by feltech** [comment]
I think this is a duplicate of https://github.com/OpenAssetIO/OpenAssetIO/issues/841

**Comment by foundrytom** [comment]
Indeed it is, thanks!
