### ISSUE TITLE
Improve Python bindings framework

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1171]
## What

Craft a pybind11 wrapper that solves various annoyances.

## Why

This was spawned from https://github.com/OpenAssetIO/OpenAssetIO/pull/1144#discussion_r1360801884 and subsequent conversations.

pybind11 has (arguably) some non-sensible defaults and is missing useful functionality:

* We shouldn't need our `PyRetainingSharedPtr` to keep Python objects alive.
* `.none(false)` should be the default for pointer-like types.
* GIL release vs. hold should be explicitly defined when binding a method.
* Argument names should be enforced to match the C++ argument names.
* Binding all overloads of a single function requires a lot of boilerplate.
   - pybind11 has a memory leak when assigning default values for arguments, in some cases.

**Comment by foundrytom** [comment]
Closing due to contention + scope being larger than there is potentially time for in the not too distant
