### ISSUE TITLE
Library version introspection mechanism

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1173]
## What

Ensure at exact version can be determined at build time and run time

## Why
- Traitgen/Mediacreation versioning needs openassetio version information for probable implementation strategies.
  - Deprecations
- Would be useful for the plugin system to know what version of openassetio they're in
- Potentially useful for pipeline engineers setting up pipelines.

## ACs
- [ ] A runtime method or property returning the openassetio version (C++ / Python)
- [ ] Major version, minor version, patch version and prelease returned in runtime accesor somehow
- [ ] Runtime accessor that returns a version string
- [ ] A compile time method of introspection such as a version header
- [ ] Can access in macros, Major version, minor version, patch version and prelease from compile time mechanism
- [ ] Version info should  require minimal manual updates

## Out of scope
- Python does not need a "compile time" equivilant version mechanism

**Comment by feltech** [comment]
As with all things, there is a PEP for this: https://peps.python.org/pep-0396/
