### ISSUE TITLE
`apiComplianceSuite` design

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1191]
## What

Determine whether there is a clear "better solution" for the design of the `apiComplianceSuite` that can be realized in a manageable time frame, before other manager plugin work.

- The current system is a little outfacing, a replacement needs to have a shallower on ramp. It requires too much effort to use.
- Its out of date as adding new tests is hard, and in itself error prone as we dont test the tests.
- It is currently unclear as to what a user has to do to leverage it.

Consult existing implementors, and determine whether there is quorum on an agreed path forward that addresses the above.

If there isn't an obvious direction by end of sprint then this topic is parked.

**Comment by feltech** [comment]
A further idea to add is to `createChildContext` at each point in the test hierarchy, and update the locale at the same time, allowing managers full control of the backend based on broad test granularity.  E.g. this could be used for testing caching.

**Comment by elliotcmorris** [comment]
https://github.com/OpenAssetIO/OpenAssetIO/issues/1240
