### ISSUE TITLE
Strategy for out-of-bounds index given to success/error callbacks

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1196]
## What

Bounds check indices passed to success/error callbacks in convenience signatures. 

## Why

Avoid segfaults and undefined behavior by accessing out of bounds elements.

## Acceptance Criteria

If an out of bounds index is passed to a success/error callback, we should throw a nice exception with a human friendly `.what()`.

**Comment by elliotcmorris** [comment]
We should likely use .at() here rather than direct access. The manager is the one in control of the index here, it's a safety concern.
