### ISSUE TITLE
Publish build artifacts as assets on release page

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1201]
Publish artifacts as release assets when we do a release.

### Why
We want to use these for pinning, in order to enable multi-platform workflows. See https://github.com/OpenAssetIO/OpenAssetIO/issues/1181#issuecomment-1810176081 as to why this is higher prio now.

## ACs

- Every tag (ie release) publishes the build artifacts to the release artifacts page, with separate artifacts for:
  - `./build/dist`
- The "release" trigger is used to ensure they can be published to a release page which bypasses retention (unless there is also a way to do this for tags)
- Publish `./build/dist` variants for debug, rel, rel with debug etc...
- Assets are named with build, platform and relevant platform and project versions.

**Comment by feltech** [comment]
We didn't appear to have a task in the epic to actually use these release builds in downstream projects, so I've added https://github.com/OpenAssetIO/OpenAssetIO/issues/1235
