### ISSUE TITLE
Hybrid Plugin System

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1202]
## What

Add a plugin system that combines multiple plugin systemss and dispatches based on advertised capability, or priority order if multiple factories advertise a capability.

## ACs

- Uses a shared identifier to locate the conceptual same manager across each plugin system.
- Make sure this is generic so it composes the output of N plugin systems.
- Uses `hasCapability` to route.
- Picks the first if present in both.

## Implementation notes

- Ideally have a internally `RoutingManagerInterface(vector<ManagerInterfacePtr> interfaces)` as this allows eg: Cpp, GPRC Python, in-process Python.

**Comment by foundrytom** [comment]
https://lucascheller.github.io/VFX-UsdAssetResolver/resolvers/production.html
https://forum.aousd.org/t/batching-ar2-queries/818/2?u=foundrytom

**Comment by feltech** [comment]
One potentially controversial change of behaviour worth calling out, required to reduce the amount of work to implement the hybrid plugin system, is to no longer require managers to reject (with an exception) unrecognized settings passed to `initialialize` - see
