### ISSUE TITLE
Add `kManagerDriven` and `kRequired` to `PolicyAccess`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1209]
(Capturing some nascent rumination on issues that came up working on #31) 

## What

- Add `kManagerDriven` and `kRequired` to `PolicyAccess` for when a Host wishes to determine which traits a Manager requires for publishing or can provide for a future entity.
- Remove `ResolvesFutureEntitiesTrait` from MediaCreation

Such that, from the Hosts perspective, `PolicyAccess` cases are defined as follows for _entity_ trait sets:

- `kRead`: What is your policy for existing entities with the supplied trait set, and which traits are you capable of resolving data for.
- `kWrite`: What is your policy when I wish to publish entities with the supplied trait set, that I already hold the data for, and which traits are you capable of storing data for?
- `kManagerDriven`: What is your policy when I wish to publish entities with the supplied trait set, and which of the traits are you capable of providing data for (via resolve) for the yet-to-be-published entity. 
- `kRequired`: What is your policy when I wish to publish entities with the supplied trait set, and which of the traits are required.
- `kCreateRelated`: As per `kWrite` (included for parity with `PublishAccess`.

## Why

Managers may required the data for certain properties to be present in order to publish an entity.  The core API also defines the `prefilght` -> `resolve` -> `register` workflow for when a Host wishes or requires to derive some of an entities properties from the Manager during publish. For example - the location to store a render, or what frame range to export.

There is however, no way for a Host to query ahead of time which traits the Manager requires or may be able to resolve for future entities. This means that the Host has no way to present a coherent user experience without "trying first". The only indication that a Manager is even capable of resolving future data is via the tenuous [`ResolvesFutureEntities`](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/blob/4f73fb6aa062d5807c4eb8010ff792da391b7d4b/traits.yml#L221C7-L221C29) trait from the optional and distinct MediaCreation library, which provides no information about which specific traits are derivable.

We need a solution within the core API, given these are are core workflows.

Using `managementPolicy` to provide this data has the benefit that as the method does not take an Entity Reference, it is a broad application-level query which allows Hosts to preemptively manage user experience if they are not able to provide data a manager needs or the manager isn't able to provide data the host needs. The resulting low call count hopefully offsets that several calls may be needed to define final behaviour.

It also constrains this business logic to specific entity trait sets, which simplifies implementation as it removes the need (or possibility) for this to vary between entities of the same trait set, which feels beneficial in what is an already complex working environment.

It would be left to Trait definitions to define which particular properties are required or optional. A trait being indicated as supported/required/derivable by `mangementPolicy` would, by contract, required that Hosts provide those properties, and/or Managers would populate them during `resolve`.

## Notes

There are some other potential ideas to help with other areas:

### `ResolveAccess`

`ResolveAccess::kWrite` could be changed to `ResolveAccess::kManagerDriven`, as resolving for write is always the `kManagerDriven` policy case (as if the Host already has the data it wouldn't resolve it). This would be a breaking change though.

### Preflight help

An extension of this could be to add `kWrite_Collaborative` and `kCreateRelated_Collaborative` to `PublishingAccess` for when a Host will attempt to resolve derivable traits from the `preflight` reference. This would help inform the business logic in `preflight` to validate the input. It doesn't completely solve the problem though as it doesn't _guarantee_ that the Host would try to resolve _all_ the missing required properties. So it might not be worth complicating the `PublishingAcces` enum given its not a robust solution. 

An alternative could be to add an optional trait set to `preflight` that indicates which traits will be resolved during publishing. However this list only improves validation, as the host still woudln't know which traits a manager might be able to resolve without the above proposed mechanism, and it woudln't provide means to refine that list beforehand. It also has complexities when publishing multiple entity trait sets in one batch.

It would perhaps be more robust (and less intrusive) to add method(s) to pre-validate the TraitsData (that would be) passed to `preflight` instead, that return programmatically inspectable failure descriptions (this allows value ranges to be checked as well as just missing data) this, when also supplied with a list of "traits Im going to resolve during publish" it would perhaps be the most effective way to pro-actively defend against "try it an see if it explodes" workflows in relation to specific entity references and planed publishing approaches. Being entity-specific though, so is not suitable for high-level application behaviour switching so is probably not an alternative to the above proposed `managementPolicy` approach. This would also need consideration in relations to the "permissions" mechanism.

### Alternatives

 - Splitting `managementPolicy` into different methods eg: `managementPolicy` and `publishingPolicy` that simplifies the Access enums and makes it more obvious.  A much bigger scope of change though.

## ACs
```[tasklist]
- [ ] Add `kManagerProvided` and `kRequired` to `PolicyAccess`
- [x] Remove `ResolvesFutureEntitiesTrait` from MediaCreation (might already be done)
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/98
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/issues/75
- [ ] Scan docs and update any publishing examples
- [ ] Update existing publishing examples to account for kRequired/kManagerProvided
```

**Comment by elliotcmorris** [comment]
`kDerived` is an awful name for this concept, which is "whether or not the manager provides data in this trait during the publishing phase, for the purposes of driving data generation" i.e, a manager would provide a location to put your bytes in if you were a render node, or provide the encoding an image file should be written in, etc.

I propose `kManagerDriven` instead.
