### ISSUE TITLE
Hybrid exception cannot be caught as `std::exception`

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1225]
## What
This was noticed in the usdResolver, but I think it's an OpenAssetIO problem so logging here.
We have code in the usd resolver tests that triggers a python exception, and attempts to verify the error message, catching by `std::exception&`. https://github.com/OpenAssetIO/usdOpenAssetIOResolver/blob/de7b465d0af08712bc34002d45746484c40505d1/src/resolver.cpp#L168

However, what happens is that we end up catching in the Wildcard exception handler, and logging "unknown non-exception type caught"
(CI logs here, although it dosen't show the full output : https://github.com/elliotcmorris/usdOpenAssetIOResolver/actions/runs/7062456693/job/19226520598)

## Why
Unknown, very likely an RTTI issue across exception boundrys., although I wouldn't rule out a diamond inheritance problem either.  (See here : https://godbolt.org/z/e6PE5b9n4, it isn't exactly what we're seeing in the usd example, but it does show our exception heirarchy demonstrating catch behaviour strangeness.)

Another thought is a standard library incompatibility between clang 14.3 (what our CI builds+runs the usd resolver on) and clang 10.5, (what our CI builds openassetio on,) however, I did test, albeit hastily, running on a 10.5 docker image and it still didn't seem to function.

Information from my experiments:
- The error, which is a MalformedEntityReference error from bal, thrown as a BatchElementException in the openassetio middleware, is catchable as an `OpenAssetIOException` or a `BatchElementException` (or even a HybridException<BatchElementException>, i went to the effort of making that type public to check)
- When caught as one of these exceptions, typeid reports the type correctly as a HybridException<BatchElementException>
- The standard exception types show up in exported symbols, (checked with `nm`) but the `HybridException` template instantiations dont.
- Attempting to explicitly instantiate the HybridException Types in both OpenAssetIO and the calling code itself (using the same hacked version making it public,) had no effect. The idea was to force the template type information to be exported, although I could never manage it.

I'm at a bit of a loss. This isn't a super emergency, as it will only occur from a python manager implementation, using the exceptional conveniences into a C++ host, attempting to catch as `std::exception` or `std::runtime_error`. That being said it's a bit of a footgun. My instinct says this is to do with being a template exception across a module boundry, and we may need to rethink.

What I havn't done but really _should_ have done is removed USD from this whole equation and attempted to catch a hybrid exception in-process in openassetio itself, that would tell us for sure if there's RTTI export nonsense involved or not, and that's probably where i'd pick this investigation up.

**Comment by feltech** [comment]
The godbolt link in the description (minus the `virtual` inheritance) highlights the issue.

It seems the ambiguous base class of `std::exception`, shared by both `OpenAssetIOException` (via its `std::runtime_error` base) and by `pybind11::error_already_set`, means that the `HybridException` cannot be caught as a `std::exception`.

For this to work, we would need both `pybind11::error_already_set` and `std::runtime_error` to have a `virtual` base of `std::exception`, but that's out of our control.

As an aside: in our conanfile we use pybind11 2.10.1, where `error_already_set` inherits from `std::exception`  The ci-base:2022.x Docker images bundle pybind11 2.8.1, where `error_already_set` inherits from `std::runtime_error`.  This means that when using the Docker container, `catch`ing a `HybridException` as a `std::runtime_error` fails, whereas locally it succeeds.
