### ISSUE TITLE
Test on consistent cmake version

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1227]
## What
Rather than just testing on the cmake version that comes with the runners (3.21), we should consider testing on the latest cmake version.
## Why
Came up recently that cmake released a version that broke macos builds (3.28). We saw this only because our python wheel builds happened to install cmake using pip, getting the latest version.  Having our C++ builds and python builds use different versions make it hard to see at a glance if it's a python/cibuildwheels problem, or just a regular build problem.

Counterargument is that we didn't need to see this at all, it was a cmake problem and they (presumably by the time you're reading this, already have) will release a patch for it. Staying on a stable version avoids the cognitive load.

I would argue we should at least be consistent, regardless of what we pick.

**Comment by feltech** [comment]
We should pin all CI to the same version as our `cmake_minimum_required(VERSION`
