### ISSUE TITLE
Add .pyi stub files to Python package

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1252]
## What

Following on from #747, add `.pyi` stub files to our Python package covering the `_openassetio` Python extension module.

## Why

IDEs can use `.pyi` stub files located in the package to greatly enhance code-completion and documentation for Python C extension modules.

## Acceptance Criteria

- Installing via `pip install` includes an `_openassetio` directory containing `.pyi` stub files (satisfying [PEP 561](https://peps.python.org/pep-0561/)), which PyCharm (and other IDEs) can detect and use to enhance code completion.
- `.pyi` stubs are included in the binary wheels on PyPI.
-  `.pyi` stubs are installed when doing a from-source install i.e. `pip install .`
- ~~`.pyi` stubs are installed (to the source tree, just like the extension module itself) when doing a `--editable` install.~~
- Installing via `cmake --install`  bundles the `.pyi` stubs in the install tree.

# Notes

See #747 for investigation with proposed implementation.

**Comment by JeanChristopheMorinPerso** [comment]
You'll also need a `py.type` file as documented in https://peps.python.org/pep-0561/.

**Comment by feltech** [comment]
> You'll also need a `py.typed` file as documented in https://peps.python.org/pep-0561/.

:thinking: At first glance, the PEP appeared to me to focus on out-of-tree stub files.  But on a second look it does seem to cover the case of bundling stubs alongside. PyCharm doesn't seem to care about the existence of a `py.typed` file, but it is the standard so we should include it.

**Comment by JeanChristopheMorinPerso** [comment]
`py.typed` will tell type checkers that the project has types. PyCharm might (and probably) bases itself on this and other logic to cover a lot of cases and improve the IDE experience. For example, see https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages.

**Comment by feltech** [comment]
I've updated the ACs to remove the need for `--editable` install, since neither PyCharm nor Visual Studio Code seem to be able to provide code completion based on stubs installed with `--editable` (i.e. installed to the source directory, with a `.pth` file pointing from `site-packages` to the source directory).  The closest upstream issue I can find is https://github.com/pypa/setuptools/issues/3518 - however, the workarounds there don't work and I'm not convinced it's the same issue, it's more like an IDE limitation in our case.

I'd love to keep going and figure it out, but it's at the point of diminishing returns when there's more important stuff to work on at the moment 😦 .
