### ISSUE TITLE
Convert long Windows paths to UNC non-normalised device paths in `urlToPath`

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1257]
## What

When a Windows path is extracted from a `file://` URL in `FileUrlPathConverter.pathFromUrl`, and that path exceeds the Windows `MAX_PATH` limit, automatically transform the path to a non-normalised UNC device path (i.e. of the form `\\?\C:\`, or `\\?\UNC\host\share`).

## Why

A common problem in real-world scenarios is the inconsistent handling of long file paths on Windows hosts/applications. 

Currently, `pathToUrl` loses any information about the type of (UNC) path provided to it, and so `pathFromUrl` will convert a Windows file URL to either a Windows drive path or a standard UNC share path, irrespective of the length of the path.

This means that e.g. a path longer than `MAX_PATH` fed into `pathToUrl` as a `\\?\...` path will come back out via `pathFromUrl` as a standard `C:\...` or `\\host\share\...` path, which might be rejected by the Windows API, depending on the particular Windows machine configuration and application where it is used.

## Acceptance Criteria

- Windows paths longer than `MAX_PATH` are automatically converted to UNC non-normalised device paths, e.g. either `\\?\C:\` or `\\?\UNC\host\share`.
- Assume we won't add an option for this, and will automatically convert when MAX_PATH is broken.
- Update docs, including `file_path_url_converter.ipynb` in the MediaCreation repo

**Comment by elliotcmorris** [comment]
We got direct feedback from the TSC that this is quite very important.

**Comment by feltech** [comment]
Looking at https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation it mentions drive paths, but doesn't say if UNC paths are similarly limited. 

So, some experiments on my local Windows...

The `MAX_PATH` limit is 260 chars, including the null terminator.

Creating a test file, 255 char filename (256 with null terminator)
```
C:\w
λ echo "It worked!" > 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789abcde
```
(confirmed an additional character results in `File name too long`)

Interestingly, we can read this file just fine with an absolute path, which is 261 chars (including null terminator)

```
λ cat C:\w\0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789abcde
"It worked!"
```

Putting the 255 char filename in a 255 char directory works fine
```
λ cat C:\w\012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345\0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789abcde
"It worked!"
```
(confirmed I can't create a directory longer than 255 chars: `The filename, directory name, or volume label syntax is incorrect.`).

This doesn't seem to match the docs. Perhaps I need to rethink my approach...

TBC
