### ISSUE TITLE
Incorrect call signatures in `Transactions.dox` code snippets

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#129]
# What

Code examples in [doc/src/Transactions.dox] incorrectly call `register`.

_Originally posted by @feltech in https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/117#discussion_r761907228_

**Comment by elliotcmorris** [comment]
Closing due to out of date, transactions have been removed.
