### ISSUE TITLE
Strip down `apiComplianceSuite` to basics

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1338]
## What

Simplify the `openassetio.test.manager` `apiComplianceSuite` test cases to check only the most basic edge cases.

## Why

The API Compliance test suite is designed to provide manager plugin authors with a host application that automatically exercises their plugin, to check for defects. This is extremely valuable, but doing it in a user-friendly and maintainable way is tricky, and work on the test suite has stalled, with some cross sections of the API simply not tested.  We plan to rework the test suite in #1240, which will require devoting significant engineering time.

As a first step to tide us over until we can prioritise the re-work, I propose that the existing suite should be stripped down to its bare essentials. We should remove any test that 

* Could conceivably be deemed "business logic" that is not directly part of the API contract. 
* Exercises aspects that we could reasonably expect a plugin author would test themselves.
* Assumes behaviour that is not documented in OpenAssetIO API documentation.

We should be especially suspicious of anything that requires plugin-defined fixtures - these are difficult to understand and maintain.

Any missing parts of the API should be covered with similar basic tests.

**Comment by feltech** [comment]
On reading through the `apiComplianceSuite` I think the number of changes to strip it down would be quite small - most of the tests do seem valuable.

**Comment by SamCrooksFoundry** [comment]
Discussed with @feltech, There's little to remove from the api compliance suite so we don't think there's a great deal of value in this ticket at the moment.  We might revisit in the future.
