### ISSUE TITLE
Fix loading C++ plugins from Python

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1340]
## What

Allow C++ plugins to be loaded from a Python environment for both CMake shared library installs as well as PyPI pip installs.

## Why

Currently, C++ plugins cannot be loaded by our PyPI package, because the Python extension module `openassetio._openassetio` statically links in the core C++ library, and hides all its symbols, so the plugin cannot link when loaded at runtime.

There are three issues at play here
- The `_openassetio` library hides all symbols from the (static) core C++ library, so the plugin cannot link when loaded.
- Python (on POSIX) loads with `RTLD_LOCAL`, meaning the symbols are unavailable to subsequently loaded libraries, even if they are public.
- Ideally the plugin would have no dependency on the core OpenAssetIO C++ library, and would instead rely on symbols being already available in the process environment when it is loaded. 
    - However, even if the `_openassetio` library and core C++ library are split into two shared libraries, `RTLD_LOCAL` is transitive, so would apply to the core C++ library too. So the plugin cannot rely on the symbols being present in the environment.
    - Windows is another question, and probably enforces `RTLD_LOCAL`-like behaviour regardless (needs more research).
    - A workaround, therefore, and possibly necessary (depending on Windows), is that the plugin must explicitly depend on the OpenAssetIO core C++ library.
 
Original investigation: https://github.com/OpenAssetIO/OpenAssetIO/issues/1324#issuecomment-2197460862

**Comment by feltech** [comment]
Add a CI job that pip installs OpenAssetIO and uses simpleResolver to resolve from SimpleCppManager. This will test linkage etc.

**Comment by feltech** [comment]
Note that building as multiple shared libraries still isn't ideal in the Python case. Python will transitively load `libopenassetio` but still not expose its symbols, so C++ plugins still won't load _unless_ the plugin has its own dependency on `libopenassetio`.  I.e. the plugin cannot trust that the necessary symbols will be available in the process environment.

**Comment by feltech** [comment]
Updated description to focus specifically on the Python package, since that's the end goal. We should still consider warning users that static library builds are unsupported.

**Comment by feltech** [comment]
Relevant Windows documentation for Python library loading: https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew

**Comment by feltech** [comment]
I tested loading the SimpleCppManager C++ plugin in Windows, with split core library and Python module, where the two libraries live in the same directory, and it loads fine. I.e. the SimpleCppManager plugin has an explicit dependency on openassetio.dll, which is already loaded into the process when the plugin is loaded, so it doesn't have to search for it.

Ideally we'd compile in a Windows [manifest](https://learn.microsoft.com/en-us/windows/win32/sbscs/manifest-files-reference) to mirror the Linux and macOS RPATH mechanism, giving some consistency between platforms.

**Comment by feltech** [comment]
Interesting [stackoverflow for Windows equivalent of RPATH](https://stackoverflow.com/questions/107888/is-there-a-windows-msvc-equivalent-to-the-rpath-linker-flag)

**Comment by feltech** [comment]
As a good example of prior art, I checked PySide2 on both Linux and Windows.  In both cases, PySide2 must also install Qt (C++ library) to the Python environment...

On Linux it installs Qt to a `Qt` subdirectory inside the `site-packages/PySide2` directory.  The Python extension modules are built with a RUNPATH of `$ORIGIN/Qt`, so the `Qt` subdirectory is added to the library search path.

On Windows, all the Qt dlls are dumped directly inside the `site-packages/PySide2` directory, i.e. in the same directory as the Python extension modules. So the Qt dlls are on the search path augmented by Python (as explained above https://github.com/OpenAssetIO/OpenAssetIO/issues/1340#issuecomment-2203488458)

**Comment by foundry-markf** [comment]
> Note this is since 3.8. We still support 3.7, which we either stop supporting, or we use the intersection of old and new behaviour, which seems to leave

What use cases do we have for Python 3.7?

Speaking in terms of VFX reference platforms, that's VFX20 & 21, so I would be surprised if we have any active development in products in that era now.

**Comment by feltech** [comment]
> What use cases do we have for Python 3.7?

I don't think any right now. We had some early adopters in studios that were providing some feedback, and they were stuck on 3.7.  I do want to remove 3.7 from the test matrix (walrus operator FTW). I'll ask around to see if anyone cares.
