### ISSUE TITLE
Add `pyright` check to CI

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#136]
## What

Add https://github.com/Microsoft/pyright check to CI.

## Why

As it catches many good things `pylint` doesn't.

**Comment by feltech** [comment]
Most of the core library has been migrated to C++ now. Additional linters are good, but we need to think more holistically about what set of linters we should use to cover the best cross-section of issues. Regardless, this won't get done any time soon. So closing for now pending that more holistic look at some undetermined time in the future.
