### ISSUE TITLE
Pin `npm` version in docs `Dockerfile`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#166]
## What

We currently install node via the LTS install. This makes the image non-deterministic. We need to pin the node version.

## Why

Prevents unintended changes when incrementing the Docker container version.

**Comment by elliotcmorris** [comment]
https://github.com/OpenAssetIO/OpenAssetIO/blob/f10a4d79efa0c2c2bf10ff15956d04e203bcf007/doc/doxygen/Dockerfile#L17C16-L17C16

**Comment by feltech** [comment]
This has never ever causes us problems, like, ever. And using the latest LTS is probably a good thing security-wise.
