### ISSUE TITLE
Verify usage of `Context.managerOptions`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#187]
## What

Check the design and intended use patterns for `Context.managerOptions` and decide:

 - ✅ Everything is fine
 - 🔧 It needs so tweaking
 - 🤯 It makes no sense and we should remove it

## Notes

The old `Hiero` implementation should contain this being used in vain.

**Comment by elliotcmorris** [comment]
`managerOptions` was deleted from context.

**Comment by elliotcmorris** [comment]
Closing due to non-existence.
