### ISSUE TITLE
`apiComplianceSuite` `Test_managementPolicy` should assert on valid return value not just type

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#236]
Currently the `apiComplanceSuite` test `Test_managementPolicy` asserts the returned value from `managementPolicy` calls is an `int` but does not further assert that the integer is one of the allowed values.

**Comment by foundrytom** [comment]
It is a bit-field, so do we need to test it is less than the max constituent flag value?

**Comment by feltech** [comment]
> It is a bit-field, so do we need to test it is less than the max constituent flags value and greater than zero?

I think we should test all allowed values, i.e. all allowed bit combinations, if this happens to also be within a specific integer range then all good, but it doesn't look like that's the case at the moment (I suspect intentionally to allow room to grow).

**Comment by elliotcmorris** [comment]
managementPolicy returns a traitset now, closing.
