### ISSUE TITLE
Investigate open source asset management systems

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#303]
## What

Investigate commercially and openly available asset management systems and "pipelines in a box" to determine options for end to end testing a and open deployments.

## Why

In order to build representative real-world scenarios for OpenAssetIO host integration design, planning and testing, we need representative pipelines with a manager containing assets.

## Acceptance criteria

- An outline of the ecosystem of readily available (ie. non proprietary) asset management systems that could implement a manager plugin for OpenAssetIO.
-  Suggestions for a potential setup for end-to-end and integration tests for OpenAssetIO integrations that is compatible with an open source/public process.

**Comment by steve-adamsATfoundry** [comment]
**Acceptance criteria**

1. An outline of the ecosystem of readily available (ie. non proprietary) asset management systems that could implement a manager plugin for **OpenAssetIO.**

- [ ]  documented internally and presented to the team

2. Suggestions for a potential setup for end-to-end and integration tests for OpenAssetIO integrations that is compatible with an open-source/public process.

- [ ]  ongoing investigation and set up of open-source assets and suitable VFX project pipelines using existing third-party asset managers suitable for VFX clients.

**Comment by steve-adamsATfoundry** [comment]
< for Review >
Below is a text summary that might provide more open-source exposition:

**Asset manager set up for OpenAssetIO for QA Engineer testing**


**1.0 - Overview**
Knowledge page for QA Testing of cloud-based asset management databases, in the context of 2 x virtual pipeline projects: (in no particular order of priority at this stage)

Project 1 represents a typical Film pipeline 2D/3D Projection workflow

Project 2 represents a timeline editing and conform workflow 

Project 3 will represent a USD based Lighting (Katana) and Compositing (Nuke) workflow

It should be noted, that ideally, these will be open-source project pipelines.

This page serves as a result of the OpenAssetIO in Nuke interface being developed by The Foundry Visionmongers.

> “a pipeline is much the same as an assembly line, in which each worker performs their task before handing off their completed work to the next.” - 
> Renee Dunlop, 2014

A VFX pipeline informs artists how an asset moves through production, where information is stored, who works when and on what. It is developed with efficiency in mind and to keep projects organized.

![image](https://user-images.githubusercontent.com/98748091/161525664-807df22c-ccd7-4623-a5fb-9e1c4a88d250.png)


**1.2   Why OpenAssetIO?**
As the diagram shows above, the OpenAssetIO serves as an interface acting between our desktop apps like Nuke and Katana, and the cloud-based server system where the film project is stored, containing all our shots and assets (entities) shared amongst potentially hundreds of people.
Perhaps the key benefit is the effortless interchange flow of information without any file conflicts (eg paths): that is, all files can be dragged locally > iterated upon by the user > and shared again with all others on the cloud asset manager, and this can be communicated and updated in a way that drives the production forward.

 

**1.3  Asset Manager setup (for QA)**
Set up Instructions:
1. Navigate to your localized project folder path



2. navigate to the following cloud asset manager webpage:
Currently, this is set up only for FrameIO cloud asset manager service:
[Frame.io](https://app.frame.io/) 

3. Create a basic account

4. Migrate the local folders from step 1 onto the cloud asset manager

5. wait for the data transfer (this may take several minutes)

6. Ensure you have the latest  build of Nuke from the correct install repository, with the relevant OpenAssetIO GUI features for testing



**2.0 - Test Projects:**

**2.1  Film VFX Camera Projection workflow**
 
![image](https://user-images.githubusercontent.com/98748091/161526411-5bd04756-5437-4d6c-8e87-0d3c76e79d18.png)

Pic: A typical modern VFX Pipeline.  source:[Andrew Whitehurst . Net](http://www.andrew-whitehurst.net/pipeline.html) 


**2.2 - Representative VFX Camera Projection folder structure**
In the image above, this VFX pipeline is factoring in a multitude of departments. 

For the initial testing and planning of this document, we will omit a number of these and create a scaled-down folder structure supporting one area of Film VFX production: 3D Camera Projection


Project   
       \
   Shot ##
          Assets
                  \ 

            -  Reference  / footage library
            -  3D 
                     - scenes
                     - models
                     - textures 
                     - cameras
                  
            -  2D  

                      - DMP (matte painting)

                      - Render_Passes

mattePainting 

                 FX
                      \
                        - particles
                        - renders

                 Comp
                         \
                       - scripts
                       - tests
                       - versions
                       - OUTPUT  
                                    > final renders



**2.4  Timeline Edit and Conform workflow**

![image](https://user-images.githubusercontent.com/98748091/161526638-7e2c1369-deee-4696-af4a-7431323e13be.png)

This is another typical workflow suitable for Users of the OpenAssetIO interface



3.0   VFX Shot Naming Convention (Typical)

As a guide, this will follow a typical shot and name version convention that might be constructed for your project testing. The link below breaks this down in more detail
https://help.prodicle.com/hc/en-us/articles/360037503233-VFX-Shot-and-Version-Naming-Recommendations

**Comment by foundrytom** [comment]
Closing due to work with Ynput
