### ISSUE TITLE
Decision record for `C` handle design

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#325]
## What

Document the rationale for the choice we made when implementing `C` handles to `C++` objects in the `C` API.

## Why

#320 highlights several options for how we could factor the opaque `C` handles that represent `C++` objects. In discussion, there are many different takes on this, and several loosely aligned factions.  We should capture this discussion before we forget, and have to scratch our heads to explain it later 🙃.

**Comment by elliotcmorris** [comment]
Closing this in lieu of a more cohesive rethink of the c-api in the distant future.
