### ISSUE TITLE
Add `Host`/`HostInterface` to C++

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#331]
## What

The mirror of `Manager`/`ManagerInterface` for the host representation.

## ACs

- `Host` class in the `managerAPI` C++ namespace.
- `HostInterface` class in the `hostAPI` C++ namespace (incl. `HostInterfacePtr`).
- Support for:
  - `identifier`
  - `displayName`
  - `info`
- Issue for `C` implementation, with any design notes.
- Python bindings as the base for existing Python `Host`/`HostInterface` classes
- Existing `test_host.py` tests used for coverage
   - Additions for the handling of edge cases where invalid values are supplied to constructors/etc.

## Out of scope

 - `_interface`
 - loggin/audit

**Comment by feltech** [comment]
Added C API issue as #423. Nothing jumped out as particularly onerous during development in #422.
