### ISSUE TITLE
Re-visit `ManagerInterface` et. al. documentation

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#361]
## What

Check that constraints described in `ManagerInterface` and `Manager` documentation, and then `HostInterface`/`Host` etc. match reality and amend/update/ensure tested accordingly.

## Why

There are several [claims in the documentation](https://github.com/TheFoundryVisionmongers/OpenAssetIO/blob/146a8a988517520f9dab603244b7c282c0df32d9/src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp#L175), that are either incorrect (as we've been more lenient), or untested in the `test.manager` API compliance suite. 

This needs to be consistent one way or another, as everyone will be reading these docs and basing their implementation on them.

**Comment by elliotcmorris** [comment]
Closing in lieu of an upcoming, more audit focused strategy for preparing docs for release.
