### ISSUE TITLE
[Build] Support sanitizers on all platforms

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#381]
## What

Support `asan`, and potentially `ubsan` sanitiers on macOS and Windows equivalents.

## Why

We presently only support these on Linux. It's possible that there may be platform specific issues.

**Comment by feltech** [comment]
Sanitizers on other platforms would help devs who prefer those platforms; and might catch very platform-specific issues. But it's hard to justify spending the time to implement this, given the small amount of problems that wouldn't get caught on a linux build.
