### ISSUE TITLE
C API for Host/HostInterface

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#423]
# What

Following on from #331, add the C API wrapper around `Host` and `HostInterface` classes.

# Notes

Should be very similar to the C API for `Manager`/`ManagerInterface`, in that `HostInterface` should be a function pointer suite provided by the host, with a `CHostInterfaceAdapter` that can be passed to the C++ `Host` constructor.

Also, similar to the `Manager` C API, the requirement for a `HostInterface` C handle is dubious.  It may make more sense to have a `Host` handle factory function, which loads a `HostInterface` function pointer suite into a `CHostInterfaceAdapter` and constructs a C++ `Host`, returning the `Host` C handle directly, and so never actually requiring a `HostInterface` C handle to be exposed in the API.

**Comment by elliotcmorris** [comment]
Closing due to C-API needing more holistic thinking later on.
