### ISSUE TITLE
Remove Python `Host` class

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#427]
# What

Migrate remaining methods from the Python implementation to the (bound) C++ implementation.

# Why

For expediency, the `Host` class was not fully migrated from Python, leaving methods such as `__str__` in place.  

~We should migrate this sooner rather than later, since the `HostSession` takes a `Host` C++ instance by-value, stripping the instance of any Python-augmented functionality when `HostSession::host()` is called to get it back.~

**Comment by foundrytom** [comment]
I _think_ it's fine to get rid of this now, as this is only there for logging/audit, which sound like it'll be lost in all practical situations where a manager gets the host from the `HostSession`
