### ISSUE TITLE
Update coding standards + guidelines

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#434]
## What

Update the in-repository dev docs to cover/refactor information on:

- C API design for
  - Method signature/memory management considerations (eg, when to pass in a handle)
- Python binding use of Ptr holders
- C++ use of Ptr vs reference vs value

## Why

We are regularly discussing/refining our approach to this, and its all in our heads at the moment!

**Comment by feltech** [comment]
This looks to be done, at least mostly.
