### ISSUE TITLE
Vagrant build steps CI check

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#437]
# What

Add CI checks for the Vagrant build instructions, timed (e.g. nightly) and when related files are touched.

# Why

We have a Build Instructions CI check for the Docker instructions, but not for the Vagrant instructions. We also found that after a while upstream changes can cause the Vagrant bootstrap to fail (i.e. additional system packages were suddenly needed for installing a Conan package), so it can break without us doing anything.  Hence a timed (e.g. nightly) CI check would be useful.

**Comment by elliotcmorris** [comment]
See https://github.com/OpenAssetIO/OpenAssetIO/issues/1280
