### ISSUE TITLE
`enable_shared_from_this` for C++ classes

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#462]
## What

Inherit from `std::enable_shared_from_this` for all classes that define a `std::shared_ptr` `Ptr` alias.

## Why

Ensures that should a value-type ever end up going through pybind, it will be handled correctly.

**Comment by elliotcmorris** [comment]
Nothing technically wrong with this, but the use case is so niche, we havn't had any issues so far and preferably we'd avoid doing this, so closing.

Might come back up if a user traffics heavily in raw pointers in an advanced case.
