### ISSUE TITLE
[CI] Improve speed of CI checks

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#484]
## What

Reduce the time that the C++ linter CI check takes

## Why

This is currently the bottleneck in our CI actions and blocks us when we have a PR ready to merge.

## Notes

Some ideas:
* Parallel builds (use Ninja)
* Disable optimisation (`O0`)
* Disable LTO
* ccache
* Cache build directory between runs
* clang-tidy discovering then suppressing 40k errors in third-party code

## Tasks

- [x] #602
- [x] #395

**Comment by foundrytom** [comment]
Did a quick experiment with `ccache`. It certainly helps, but only gives incremental savings. Building `openassetio-python` from clean on my little Mac goes from `1m 10s` to `49s` when using it as `CMAKE_CXX_COMPILER_LAUNCHER`.
