### ISSUE TITLE
[Core] Add batch-first C API functions

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#490]
# What 

Following on from #487, implement the C API for functions that output a batch of results.

# Why

The C++ API design chosen in #483 uses success/error callbacks executed on each element of the result. We need to translate this to work with the C API on both host and manager -side interfaces.

# Notes

For reference, the investigation in #487 resulted in the sketch presented in https://github.com/feltech/OpenAssetIO/tree/prototype/487-cAPIResolveSketch.

**Comment by feltech** [comment]
Dissecting the prototype linked in the description for some salient parts.

The C API can only take function pointers as callbacks. To provide a way to "capture" data from the caller, we must use the "user data" idiom, giving callbacks that look like
```c
typedef void (*oa_hostApi_Manager_ResolveSuccessCallback)(void*, size_t, oa_TraitsData_h);
typedef void (*oa_hostApi_Manager_ResolveErrorCallback)(void*, size_t, oa_ErrorCodeAndMessage);
```

Since the C++ sketch of the `resolve()` API includes `const` references, we will require work to add `const` variants of our opaque C handles (tracked separately in ADD ISSUE HERE).  With that done, the `Manager` C API looks like

```
OPENASSETIO_CORE_C_EXPORT oa_ErrorCode oa_hostApi_Manager_resolve(
    oa_StringView* err, oa_hostApi_Manager_h handle, oa_ConstEntityRefs_h entityRefsHandle,
    oa_ConstTraitSet_h traitSetHandle, oa_ConstContext_h contextHandle,
    oa_hostApi_Manager_ResolveSuccessCallback success,
    oa_hostApi_Manager_ResolveErrorCallback error, void* userData);
```

The implementation of this unpacks the handles to their C++ types and calls the C++ `resolve` method, providing C++ callbacks that wrap the function pointer callbacks (via a capturing lambda), in order to convert the results to handles and pass them on to C.

**Comment by feltech** [comment]
Much of our discussions and prototyping focussed on the batch interface for `resolve`.

For `managementPolicy` (and potentially similar functions), which are cheap and where it is not possible for a single element in the batch to error, we will instead opt for returning a `vector` of results, as sketched in https://github.com/OpenAssetIO/OpenAssetIO/issues/456#issuecomment-1168691147

The C API will then bind std::vector<TraitsDataPtr> as an opaque handle, and it will be the responsibility of the host to pre-allocate and pass as an out-parameter to the C API.

**Comment by elliotcmorris** [comment]
C-api requires long term holistic thinking. out of date.
