### ISSUE TITLE
`TraitsData` equality

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#493]
## What

Decide on how best to handle equality operations in `C++` for `TraitsData`.

## Why

#481 switches to C++ code only ever having a shared ptr to a `TraitsData`, this opens up the question of how best to facilitate by-value comparisons of traits datas. Currently this needs to be achieved by `*data1 == *data2`. Do we need an equality method that takes a ptr or similar?  This isn't a problem in python as there isn't a distinction between a ptr/value in the same way.

**Comment by feltech** [comment]
We think pointer comparisons in C++ are a fundamental concept and having an `operator==` overload for `shared_ptr<TraitsData>` would be counter-intuitive.  Closing.
