### ISSUE TITLE
Add `HostInterface.isInteractive` or similar

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#51]
# What

Add a method to `HostInterface` (wrapped via `Host`) to allow a manager to query (via the supplied `HostSession`) whether or not the current call context is considered to be interactive. `True` here would imply that the manager implementation may make use of user prompts/etc... during API calls such as `register` and the likes. `False` may mean the host session is running in batch more, or the API session is bring proxied out-of-process.

# Why

Certain aspects of interactive publishing flows are left up to the manager. For example, requesting comments on ancillary information. To facilitate this, the manager needs to know when it may be appropriate to present custom interfaces to the user.

**Comment by elliotcmorris** [comment]
We think this is something that goes in the locale. Closing
