### ISSUE TITLE
Document/use exceptions when manager implementation not found

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#521]
# What

Document the appropriate exception that should be thrown when a manager implementation with a given identifier is not found by a `ManagerInterfaceFactoryInterface` (/ `ManagerImplementationFactoryInterface`) when calling `instantiate()`.

# Why

Currently the correct behaviour is not documented. The Python plugin system implementation will raise an `exceptions.PluginError`, which is Python-only (currently) and perhaps too specific to plugin factories, rather than factories in general.

Documenting the expected behaviour (and obeying it in our implementations) ensures that hosts can guard against the appropriate exception, to give proper user/developer feedback.

# Notes

The Python `exceptions` module has not been migrated to C++. If we require a dedicated exception class, then this should be available in C++ (and bound to Python).

**Comment by elliotcmorris** [comment]
Might fall out of the wash in : #1115 

Note: There's an incorrect doc in `PythonPluginsystemManagerImplementationFactory.py`, saying it still returns `PluginError`
