### ISSUE TITLE
Pin conan recipes

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#551]
## What

Pin conan recipes to specific versions.

## Why

We've been bitten by recipe variations breaking CI/build.

**Comment by foundrytom** [comment]
https://docs.conan.io/en/latest/reference/commands/misc/lock.html

**Comment by foundrytom** [comment]
Probably worth bumping conan to latest whilst were at it.

**Comment by feltech** [comment]
This is already the case.
