### ISSUE TITLE
Python GIL Management

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#554]
## What

Establish where we need to manage the GIL, and update the bindings accordingly.

## ACs

- Ensure `CODING_STANDARDS.md` is updated to include any GIL-related guidelines.
- Impact on GIL management for the current Python -> C++ -> C -> C++ -> Python code path (and variations) is understood and mitigations implemented (currently looking like GIL release in all `Manager`, `Host`, `ManagerInterface` and `HostInterface` methods - as interface methods may be called directly (Eg: gRPC), `ManageFactory`, `ManagerImplementationFactoryInterface` etc).
- Tests cover:
   - Python calling into C++ manager interface that tries to acquire the GIL from another awaited thread (or similar).
   - (manual check that pybind does do what its docs say)

```[tasklist]
### Tasks
- [x] `gil_scoped_release` all the things
- [x] Add issue to revert usage of `OPENASSETIO_PYBIND11_OVERRIDE_PURE_NAME` once fixed upstream
```

**Comment by feltech** [comment]
Probably worth littering these around the bindings: https://pybind11.readthedocs.io/en/stable/advanced/functions.html#call-guard

**Comment by feltech** [comment]
We don't acquire the GIL within `createPythonPluginSystemManagerImplementationFactory`, so currently the host must acquire it before calling this. 

The symptom in a Release build is an unhelpful segfault. In a Debug build you get a failed assertion telling you that the GIL must be acquired before importing modules.

**Comment by foundrytom** [comment]
This is becoming more urgent - as certain integration projects have come across issues due to us not releasing the GIL in Manager Interface bindings.
