### ISSUE TITLE
Context enum restructuring

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#568]
# What

Investigate whether `enum class` (rather than old-style `enum`) can/should be used for `Context::Access` and `Context::Retention`.

If old-stye `enum`s are chosen for `Context`, then decide whether `BatchElementError::ErrorCode` should be likewise defined.

# Why

Old-style enums do not create a namespace of their own, meaning that `Access` and `Retention` values are exported to the parent `Context` class, i.e. `Context::kIgnored` lives alongside `Context::kUnknown`, as opposed to `Context::Retention::kIgnored` and `Context::Access::kUnknown`, respectively. 

On the other hand, old-style enum constants are trivially convertible to their underlying numeric representation, whereas `enum class` constants require a `static_cast`.  This is relevant to the `Context::kRetentionNames` code-to-string mapping.

**Comment by foundrytom** [comment]
Name lookup is relatively infrequent so increasing complexity there should not be a steering factor in choosing which option - the ambiguity around cases in the day-to-day is far more troublesome.
