### ISSUE TITLE
Use `str::string` for entity reference related methods.

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#572]
## What

Use `std::string` for `createEntityRefrence` and friends, and in all methods that use `Str` that aren't container types such as `TraitsData` or `InfoDict`.

## Why

We currently have a mixture of `Str` and `std::string` in the methods on `Manager`/`ManagerInterface`.

**Comment by elliotcmorris** [comment]
When we say `and friends in all methods`, in this issue, is this intended to indicate a codebase wide purge of `openassetio::Str`, (except for container types,) or is this more targeted at just the things directly related to `createEntityReference` in the `Manager` files?

**Comment by foundrytom** [comment]
> When we say `and friends in all methods`, in this issue, is this intended to indicate a codebase wide purge of `openassetio::Str`, (except for container types,) or is this more targeted at just the things directly related to `createEntityReference` in the `Manager` files?

Sorry, yeah, there was a missing `,` (updated). #576 as a bit more detail. We'd made this ticket to remind us to do it :). This is one we wanted to pick up discussions on to decide which way to go, as the community seemed divided as to a 'alias all the things' vs 'call a spade a spade' approach.
