### ISSUE TITLE
Add user/issue link to @todo comments

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#60]
As mentioned in https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/49#discussion_r730761086, the Doxygen `@todo` comments currently have no attribution.  

It would be useful for future readers of the code to be able to link a todo comment to the user or ticket that caused it.  The convention of placing the user's initials after the todo won't work here because it is Doxygen markup, so we'd need to think of an alternative process.

**Comment by elliotcmorris** [comment]
Closing due to low importance.
