### ISSUE TITLE
Document string encoding

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#61]
Following on from #47, and based on our eventual Python 2 vs. 3 vs. C++ design decisions, we should add a section to the documentation detailing how string encoding is handled in OAIO.

**Comment by elliotcmorris** [comment]
Closing due to low importance, as well as also being docced in a DR : https://github.com/OpenAssetIO/OpenAssetIO/blob/main/doc/decisions/DR005-String-encoding.md
