### ISSUE TITLE
[Test] Improve Python install step for TDD

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#615]
# What

As a developer
I want a "fast install" option for the pure Python component when executing tests,
Because it will improve my efficiency when TDDing.

# Why 

(Re)Installing the pure Python component is required before running the unit tests. This is because we execute tests from the install tree, for better dogfooding. This installation takes approx 12 secs (on Github CI, see #602, somewhat quicker locally).

For the purposes of the TDD loop we want to speed this up.

# Notes

#395 will ensure that Python component is not reinstalled multiple times for a single test run.

#368 is closely related.

`rsync` instead of `pip install` is the easy option.

A `pip install --editable` workflow would be more canonical, but is tricky due to the C++ extension module component.

# Tasks

- [ ] Investigate whether Python `--editable` install is feasible
- [ ] Implement improvement to Python install step for TDD

**Comment by foundrytom** [comment]
Closing thanks to #629
