### ISSUE TITLE
`CMake` needs patching to build on Windows

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#623]
## What

See: https://github.com/JellyfishPictures/OpenAssetIO-rez-pkgs/blob/075d1823255446930901b3ed0eb6e0674a4e6a28/openassetio/rezbuild.py#L30

It seems that CMake is having trouble finding python on Windows in some configurations.

We need to figure out the cause for this, and support out-the-box where possible.

**Comment by antirotor** [comment]
Found two issues on Windows:

What I did:

```sh
git clone https://github.com/OpenAssetIO/OpenAssetIO.git
cd openassetio
python -m venv .venv
./.venv/Scripts/activate.ps1

python -m pip install --update pip
pip install pybind11[global]
```

I had to add manually pybind11_DIR for cmake find it. I've tried `pip install pybind11` and `pip install pybind11[global]` both without success. 

Running:
```sh
cmake -S . -B build -D pybind11_DIR=.\.venv\share\cmake\pybind11
```
solved the issue.

Bigger problem was error with linking of `python39.lib` that wasn't found no matter what I've tried. I've managed to quickly hack it by just copying the lib to  pre-configured vcpkg directory that was auto added to the linker.

Last thing I had to do was to manually copy `openassetio*.dll` and `_openassetio.pyd` to `.venv/Lib/site-packages/openassetio` to make it work.

**Comment by feltech** [comment]
To answer specifically about the patching required in the linked Rez package in the description: 

Our development/testing both on CI and locally on Windows, with both Conan and external (via `cibuildwheel`) Python environments, didn't require such a patch, so it seems like a Rez environment-specific issue. 

We are currently in the process of getting a Rez deployment to test OpenAssetIO packaging, and will be able to investigate this more thoroughly once this is set up.
