### ISSUE TITLE
Project structure and release artifacts

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#627]
## What

PyPi release of `openassetio`

## Why

Early adoption has shown that there is much confusion around the mechanics of the project build. Early prototypes with to use `openassetio` in Python. Having a ready made package will greatly simplify community PoCs.

## Work

- [x] #628
- [x] #629
- [x] #630
- [x] #657
- [x] #652
- [x] #653
- [x] #646
- [x] #648
- [x] #672
- [x] #674
- [x] #715
- [x] #654
- [x] #714 
- [x] #655
- [x] #716

**Comment by feltech** [comment]
All tasks here are complete, and we've had PyPI releases for some time now, should this be closed?
