### ISSUE TITLE
[Investigation] Modular project file structure

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#628]
## What

Produce a DR that describes a revised project filesystem structure that better reflects/supports the modularity of the code base.

## Why

The current structure has grown from a pure python project, to a pure python project with some C++ components to a C++ project with optional Python.

The current structure inadvertently has slightly spider-web dependencies that make decoupling the optional components harder, especially with those in `resources`.

Timebox: 1 day

## ACs

- DR outlining chosen structure with rationale.
- Optional (anything in resources, C, Python) components should be self contained.
- Project structure is independent of language/tooling choices used.
- Structure should facilitate the removal of an optional component without needing to update its peers (other than upstream dependencies). 
- Update #655 with tasks for implementing the DR

**Comment by foundrytom** [comment]
It occurred to me that the reason we have trouble with the `openassetio`/`openassetio-codegen` relationship is probably because we're squinting at it wrong.

The issue is that "openassetio" as a release, depends on codegen (to make the included traits), but codegen depends on "openassetio" to test the generated code.

If we change the boundaries around a little, the _actual_ dependencies look like this:
 
- `openassetio-types` = `TraitsData`, `TraitBase`, `SpecificationBase`
 - `openassetio-codegen` -> `openassetio-types`
 - `openassetio` -> codegen output, `openassetio-types`

So we don't have a cycle as such, just perhaps a less than ideal slicing of the cake?

**Comment by foundrytom** [comment]
Potentially controversial idea No. 345:

We explicitly make OpenAssetIO-Core as un-oppinionated and stable as possible. Maintaining a stable, parameterized core ABI is critical. Until we changed `managementPolicy` to use traits, there were deliberately no traits or specifications in the core. This allows each domain that uses the API to have full control over the semantics of _what_ passes through the API, leaving the core to define _how_.

We should remove `traits.managementPolicy`. They are too naive and usage-specific to be in core. 

Once these are gone, the codegen dependency problem goes away. It becomes another outer-layer tool, (probably in its own repo), that can depend on `openassetio` if it likes. This has the following benefits:

 - Core remains totally unoppinionated about the situation in which the API is used.
 - Version churn in codegen doesn't pollute the core API versioning.
 - The versions of traits are already encoded in the version of the package from which they are consumed.
 - The repetitive versions of codegen and openassetio are stated in the setup.py (or similar) for these packages.

The dependency chain for something like OpenAssetIO-MediaCreation then becomes:

  `openassetio_mediacreation` -> `openassetio_codgen` -> `openassetio`.

**Comment by feltech** [comment]
> We should remove `traits.managementPolicy`. They are too naive and usage-specific to be in core.

As in, part of the core workflow is to request a `managementPolicy(...)` and get back a `TraitsData`, but the view you apply onto that `TraitsData` is industry-dependent?  :thinking: 

I guess that could work, since nothing in the core actually uses the policy, it's up to the host application to interrogate it (IIRC).

If that's the case then yeah sounds good.  Some work to do re. BAL then, maybe needs to be pulled out of the repo first.

**Comment by foundrytom** [comment]
> As in, part of the core workflow is to request a `managementPolicy(...)` and get back a `TraitsData`, but the view you apply onto that `TraitsData` is industry-dependent? 🤔

Yeah, exactly. In our current use cases we only say "managed" or not, and also (still) have the legacy idea of "willManagePath".  Maybe some sector has different kinds of "managed"?

> I guess that could work, since nothing in the core actually uses the policy, it's up to the host application to interrogate it (IIRC).

Yeah, that's what made me think that it probably shouldn't be there.
 
> If that's the case then yeah sounds good. Some work to do re. BAL then, maybe needs to be pulled out of the repo first.

👍
