### ISSUE TITLE
Don't use `setup.py` in CMake

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#629]
## What

De-couple CMake and `setup.py`, so that `setup.py` can be used as a top-level entry point for installation/management of the python component of the API.

## Why

Presently, `cmake` creates a virtual environment, and uses `setup.py` to install `openassetio` into the venv. This complicates python packaging for distribution where it is expected that `setup.py` is the entrypoint for pip et al.

We need a solution that enables simple, local builds that create working python packages, as well as an intuitive install/build process for the python components.

## Acceptance Criteria

- CMake no longer uses the top level setup.py so that setup.py can be invoked to build a python distributable by pip.

## Notes

What needs to happen to make a python package:

 - `libopenasstio-core.so`/`.a` compiled (cmake) 
 - cmodule (`_openassetio.so`) compiled (cmake)
 - `_openasstio.so` copied to python package root

At this point you could extend `PYTHONPATH`/`LD_LIBRARY_PATH` and `import openassetio`, eg: in an embedded application that uses its own interpreter, and links to openassetio from C++.

If this needs to be standalone, ie, with `pip install` and `python`, `libopenasetio-core` needs to be linked by `_openassetio`. Either

- `libopenasetio-core.so` installed such that it is discoverable on the library search path. 
     -  `LD_LIBRARY_PATH`, application's transient `RPATH`, system paths, et al. can be used as a fallback (as above).
     - On Unix, `_openassetio`'s `RPATH` is currently set to a relative path that assumes the shared library is placed under the `lib` ancestor of `site-packages` (matching the CMake install tree). 
     - On Windows we currently have some rather hacky CMake code that copies `libopenasetio-core.dll` into `site-packages` in the CMake install tree. Windows has not been properly considered, beyond just getting CI running the tests.
- `libopenasetio-core.a` statically linked into `_openassetio.so`. Obviously we must then be careful that `libopenasetio-core` has not already been linked into the application through some other route.
## Proposed changes

 - CMake install command manually populates the `dist` structure as before.
   - When `OPENASSETIO_ENABLE_PYTHON_SRC_BUNDLING` is `ON` (default) then also copies `.py` source via CMake's `install(FILES)` (instead of using `pip`/`setup.py`).
   - ~Option to static link `_openassetio.so`~ (done)
- Tests run with modified `PYTHONPATH`.
- `venv.create` build (and CTest fixture) target to create test venv, conditionally built-up via `add_dependencies` as the CMake source tree is traversed. (venv isn't `dist`, can be elsewhere, and `opeanssetio` is still referenced via `PYTHONPATH`)
  - Initially replaces the related fixtures in ctest.
  - `OPENASSETIO_ENABLE_PYTHON_TEST_VENV` option that, when `OFF` (default) causes `OPENASSETIO_PYTHON_VENV_ACTIVATE` to be a no-op and skips adding `venv.create` build target as a fixture.
  - Remove `download-deps` targets and hence remove `--no-index --find-links` from `pip` install step(s).
- ~CI jobs to run Python tests with both statically linked and dynamically linked versions of  `_openassetio.so`.~

**Comment by elliotcmorris** [comment]
> CI jobs to run Python tests with both statically linked and dynamically linked versions of _openassetio.so.

Discussions between @feltech and I resolved to feeling this is out of scope for this ticket.
It seems to fit much better with the work in #630, which will involve changes to the python build. I recommend adding the idea that the `setup.py` work causes static linkage to the acceptance criteria of that ticket, along with adding new CI for that build, seems to fit much more neatly.

**Comment by elliotcmorris** [comment]
@foundrytom  Reminder to discuss : during the work we were talking about how the codegen install target still uses its own `setup.py`, which is fine as it's pure python so there's no circular dependency. However it may be more correct to `pip install` this, or even to use the newly established cmake install pattern we're now using for it. Worth a chat.
