### ISSUE TITLE
Batch API `index` and/or `reference`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#640]
Should the batch-centric entity related methods in the API use an index, or the reference as the first argument (or both)?

It occurred to me that _not_ providing the reference could make it harder to switch to a model in the future where the callbacks were async? Though maybe it doesn't matter as you'd have to capture some other data in the callback anyway, unless we wanted a 'user data' style arg too?

Ie:

```
callback(index, result) [current]
callback(index, result, userData=None)
callback(index, reference, result)
callback(index, reference, result, userData=None)
```

Timeboxed: 0.5 days

**Comment by feltech** [comment]
Both C++ and Python callbacks can be closures with access to variables in the outer scope, e.g. the input batch, meaning that the input batch element's index is the only extra information technically required.

C API callbacks (i.e. function pointers) of course can't use closures.  In previous sketches we have used a `userData` argument (see #490 and #570), though we didn't sketch out a full `resolve` workflow from the host's perspective.

**Comment by foundrytom** [comment]
So feels like we should just stick "as is", except for C, where we'd include a `void*` too?

**Comment by feltech** [comment]
I think we can split the potential reasons to include the entity reference in the callback signature into two camps: convenience vs. necessity.

It'll be worth sketching out workflows, or indeed auditing workflows we already have or are working on (OTIO, AR2, MovieLabs), to see if there's a good reason to include the entity reference as a convenience.

It may still turn out that there is a reasonable case where we _have_ to provide the input entity reference to each callback.  But I do struggle to think of any off the top of my head.

And surely there's some prior art out there somewhere.

**Comment by foundrytom** [comment]
Closing pending more info about host contexts.
