### ISSUE TITLE
PyPi publishing

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#653]
## What

PyPi packages published for:

 - `openassetio`

## ACs

- `pip install openassetio` installs a working python package in a clean environments on CY2022 python platforms [~Mac~/win/linux] (such that module are importable).
- Packages are auto-published based on a release being created in GitHub.
- Manual publish steps are known/documented in the case of GitHub downtime.
- Python versions: 3.9, 3.10 (x86_64)
- Linux: Needs to work on (Centos 7, and Ubuntu 20) [tested via pip install + pytest during release]
- Builds steps are idempotent

## Out of scope

- Windows ARM
- ~macOS~
- i386

## Implementation notes

 - It is beneficial to publish per platform/version when succeeded vs blocking all on one failure

- See OTIO for prior art in multi-dist wheel builds and pre-publish testing (testpypi) and check with JC where we plan to diverge.

Do this in same workflow : 
- On merge to `main`/`release` 
  - Using ManyLinux images, build wheels on matrixed platforms.
  - Once all wheels are built, upload all to testPyPI on an Ubuntu runner.
  - matrix test the uploaded wheels using pip install from testpypi and `python -m pytest` on all built platforms
- Only On `release`
  - upload to PyPi, after all prior steps have finished.

**Comment by elliotcmorris** [comment]
When attempting to run the pyPI publish action on non-linux platform, we learned something, an error : `Container action is only supported on Linux`

This is the official action, and is a known issue. It's even mentioned right there in the README : https://github.com/pypa/gh-action-pypi-publish#non-goals

We could work around this problem, by directly doing a twine upload. However, we're given pause by the justifications in the README, which very strongly encourage a bundled upload after all the builds have been completed. As this is the official package, we're going to listen to their advice, and use the suggested upload/download trick to upload all the wheels at once in the same workflow.
