### ISSUE TITLE
[Investigation] PyPi Publishing

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#657]
## What

Investigate PyPi publishing and pre-publishing testing to inform #630 and #653.

Timeboxed to 1 day initially.

## ACs

- Notes on the proposed strategy for PyPi package publishing.
- Notes on any design considerations for #630 that will be required to support future publishing.

## Notes

See OTIO and skeleton OTIO plugin projects for prior art.

**Comment by elliotcmorris** [comment]
See #653 for notes on outcome. 

Tldr: It's going to work, we're not supporting non x84_64 platforms initially, MacOS is still deferred for the moment, only python3.9 - 3.10 strait out of the box, although that's soon planned to be moved to 3.7+
