### ISSUE TITLE
Re-instate support for Python 3.7

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#660]
## What

~Decide which Python (minor) versions to support~

Early adopters have stated the need for Python 3.7. We need to ensure there are no newer python features in the code base, and update CI and build infrastructure to use 3.7 by default, but also build for latest. Packages should be published for 3.7 -> latest.

## Why

This affects which Python features we can use (e.g. `list[str]` type annotation is 3.9+) , our CI config, and other ongoing maintenance burdens.

## Tasks

- [ ] Wrap implicit casts of Enums to int
- [ ] #662

**Comment by foundrytom** [comment]
We need to support 3.7+ if possible, based on feedback from early adopters.

**Comment by foundrytom** [comment]
We should downgrade CI to the earliest version supported when we do this, to ensure we don't accidentally use newer language features.
