### ISSUE TITLE
Decide on thrid-party library version pinning strategy

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#667]
# What

Decide a strategy for pinning the versions of third-party dependencies (e.g. C++/Python runtime/build dependencies).

# Why

Pinning third-party dependencies to a specific version means builds/runs are reproducible so that any errors that occur are due to the work at hand, rather than due to a new incompatibility with a dependency. However, this means we should have a strategy for regularly scheduling manual updates to dependencies, to remain current.

Alternatively we can try to use the latest available at all times and tackle problems when they occur. This forces us to keep current, but can introduce churn in work for unrelated (i.e. third-patry) problems.

We currently have a mixed strategy for this
* Conan package versions are pinned.  For some packages, VFX reference platform constrains this somewhat.
* Conan package recipes are unpinned. This has caused headaches in the past, causing CI jobs to fail when recipes are updated.
* Python build dependencies are unpinned (minimum version only).
* Python runtime dependencies (tests, codegen) are pinned.
* Build dependencies and Github Actions (both `pip install`ed tools and actions themselves) are a mixed bag.

**Comment by foundrytom** [comment]
Dependabot also does `pip`, fwiw.

**Comment by feltech** [comment]
We've naturally ended up pinning as much as possible since this issue was created. It's also a case-by-case basis and a global strategy probably isn't workable.
