### ISSUE TITLE
Update GitHub action versions

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#668]
## What

 - Update the pinned versions of git hub actions (Eg: `checkout` etc..)
 - Decide if versions for core GitHub sourced actions should be pinned (vs third party)
 
## Why

- The versions we are using are deprecated, see https://github.com/elliotcmorris/OpenAssetIO/actions/runs/3291239068

**Comment by JeanChristopheMorinPerso** [comment]
I would recommend dependabot to manage updates of GH actions.

**Comment by foundrytom** [comment]
Dependabot configured.
