### ISSUE TITLE
Extended Python support

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#682]
## What

Extend our officially supported Python versions to include 3.7 and 3.11

## Why

We know 3.7 is still in use in production. 3.11 helps us stay on top of evolutions in the language so future adoption becomes less of an issue.

## Tasks

- [x] #660
- [x] #683

**Comment by feltech** [comment]
I think this should be closed (?).  All tasks are marked as done.  We now build wheels for 3.7 and 3.11.  Tentatively closing this.
