### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#683]
## What

Ensure `openassetio` wheels can be built for Python 3.11

## Why

Ensures we don't get too far out of sync with Python as it evolves

## Tasks

- Update pybind to 2.10.0
- Update tests to cover re-worded exceptions [should we be validating the actual message when it originates from outside of our code?].

**Comment by feltech** [comment]
There isn't yet a ConanCenter package for Python 3.11 and I can't find any open issues/PRs on the ConanCenter recipe GitHub, so it may be a while.

Currently we only `ctest` against 3.9 anyway, so perhaps no big deal if Conan doesn't have 3.11 yet.  Though the fact that it's not a drop-in replacement gives me pause.
