### ISSUE TITLE
USD AR2 interop

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#685]
## What

Produce a [USD AR2](https://graphics.pixar.com/usd/release/wp_ar2.html) plugin that is an OpenAssetIO host, allowing OpenAssetIO Manager Plugins to be used for USD asset resolution etc, including Python based plugins.

## Tasks

- [x] https://github.com/OpenAssetIO/usdOpenAssetIOResolver/issues/1
- [x] OpenAssetIO/usdOpenAssetIOResolver#5
- [x] OpenAssetIO/usdOpenAssetIOResolver#4

**Comment by elliotcmorris** [comment]
If you've not seen it, there's a USD AR2 resolver example that comes along with the USD install, I found the overview for it pretty illuminating. [Link.](https://github.com/PixarAnimationStudios/USD/blob/release/extras/usd/examples/usdResolverExample/overview.dox)

**Comment by foundrytom** [comment]
All done.
