### ISSUE TITLE
Guard against running the PyPI release step in any inappropriate branches/repos.

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#704]
Currently, the only guard against accidentality releasing a PyPI build is whether or not the repo has the appropriate secret or not.

Since we've ran testPyPI uploads somewhat frequently, and since the GUIs for a fork and the main repo are identical lookin', it may be prudent to put some hard protection into the upload-to-pypi step in the github action, so it can only run on the true openassetio::main branch.

This isn't super vital, but given the general level of empty-headedness [_some_](https://github.com/elliotcmorris) members of the team have, it may be smart.

**Comment by feltech** [comment]
We think the presence/absence of the secret is a sufficient guard against this problem.
