### ISSUE TITLE
[Investigation] `pkg_resources` Python manager plugins

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#712]
## What

OTIO has a [neat trick](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/b52667d18b4cfa5d3e1f8128b93ebb39fc4d3b73/src/py-opentimelineio/opentimelineio/plugins/manifest.py#L253), in that it also supports discovery of plugins via `pkg_resources`. 

Investigate the suitability of this for loading python-only manager plugins.

## Why

This greatly simplifies the distribution of [otio] adapters/etc. as there is no longer any need to manually download and add them to custom search paths. We've seen the value of "low friction" workflows with the PyPI publishing work.  OpenAssetIO has an identical mechanism (get a plugin, put it on a custom path), and our plugins are legal python modules, so this approach could significantly streamline the distribution and update of manager plugins in less complicated pipeline scenarios.

OTIO provides a simple way to [disable this mechanism](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/main/src/py-opentimelineio/opentimelineio/plugins/manifest.py#L13), which would make equal sense in OpenAssetIO too.

**Comment by foundrytom** [comment]
Turns out this was pretty trivial, which (unfinished) hack, that seemed to work:
  - https://github.com/foundrytom/OpenAssetIO/commits/work/712-pkgResourcesPlugins
  - https://github.com/foundrytom/OpenAssetIO-Manager-BAL/commits/work/712-pkgResources

```shell
cd /tmp
git clone --branch work/712-pkgResourcesPlugins git@github.com:foundrytom/OpenAssetIO.git
git clone --branch work/712-pkgResources git@github.com:foundrytom/OpenAssetIO-Manager-BAL.git
python -m venv .pkg-resource-test-env
. ./.pkg-resource-test-env/bin/activate
export CMAKE_TOOLCHAIN_FILE=...
python -m pip install ./OpenAssetIO
python -m pip install ./OpenAssetIO-Manager-BAL
cd ./OpenAssetIO/resources/examples/host/simpleResolver
export OPENASSETIO_DEFAULT_CONFIG=bal_animals_openassetio_config.toml
export OPENASSETIO_LOGGING_SEVERITY=0
python ./simpleResolver.py named bal:///cat
```

**Comment by feltech** [comment]
The one remaining thing to potentially investigate is whether the `pkg_resources` trick can possibly work in a `PYTHONPATH`-extended environment (rather than `pip install`ed).  Pretty sure it won't, though.

**Comment by foundrytom** [comment]
I saw [this](https://setuptools.pypa.io/en/latest/pkg_resources.html) too:
> Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources.

Didn't have time to work out what the `importlib` equivalent was. Prob worth doing when we pick this work up properly. I just cribbed this version from OTIO.
