### ISSUE TITLE
[Build] Move `setup.py` into `openassetio-python`

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#728]
# What

~Decide on and then possibly~ Move the top-level `setup.py` under the Python component in the directory structure.

# Why

This follows on from https://github.com/OpenAssetIO/OpenAssetIO/pull/633#discussion_r1014326262. 

When originally designing #628 we had a `setup.py` that was - unexpectedly to outside adopters - insufficient to build a working Python package.  So it made a lot of sense to hide it away under the Python component.  However, this argument no longer holds - `pip install .` can create and install a fully functioning Python package (assuming C++ library dependencies can be located).

The other main argument for moving `setup.py` is that the project looked too Python-centric, when the Python component is an optional add-on.  We also wanted to "physically" separate components into different directories, and having a rogue `setup.py` outside of the Python component is inconsistent with that vision.

**Comment by foundrytom** [comment]
We def want to do this to ensure the desired compartmentalisation of components. If it turns out that this is overly onerous to realise, then we can park it.

**Comment by feltech** [comment]
Doing a quick investigation into how onerous this is.  TLDR - we need to upgrade `pip` and then `pip install .` works.

The main issue with moving `setup.py` in the past is that `pip` copies the tree from `setup.py` on down into a temporary directory, so relative paths to outside that tree (e.g. to our `CMakeLists.txt`) get broken.

Using Ubuntu 20.04's default Python 3.9 `apt` package with `pip` v20.0.2 and putting a breakpoint in the `build_ext` function in our `setup.py` finds that
```
>>> os.getcwd()
'/tmp/pip-req-build-g1ezk133'
```

After running `pip install --upgrade pip`, giving pip v22.3.1 we have
```
>>> os.getcwd()
'/home/dave/workspace/cloud/assetapi/OpenAssetIO/src/openassetio-python/package'
```

Perusing various pip issues/docs we can see that in-tree builds became the default in pip [v21.3](https://pip.pypa.io/en/stable/news/#v21-3) following a [long arc](https://github.com/pypa/pip/issues/7555) of issues with out-of-tree builds.
