### ISSUE TITLE
[Tests] Split `_openassetio_test`-related tests into two

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#739]
## What

Split the tests that depend on the `_openassetio_test` Python extension module into two independent test components

## Why

During the project restructure in #655 symmetry in the directory structure between tests and the (sub)components under test was impossible to achieve, since we bundle tests of two quite separate components under the one umbrella, namely `bridge` (`createPythonPluginSystemManagerImplementationFactory`) tests and `module` (`PyRetainingSharedPtr`) tests.

Ideally we would split those tests into their own CTest targets, under their own subdirectory, with their own `_openassetio_test`-like helper module (if required - arguably the `bridge` test should be a C++ application with embedded Python interpreter)

## ACs

- `tests` dir mirrors structure of `bridge`/`module` etc
- Tests for `bridge` are done using a simple host with it's own embedded python interpreter

**Comment by foundrytom** [comment]
We should def do this - I was just looking at the new structure and the current arrangement confused me greatly.
