### ISSUE TITLE
[Investigation] Create `.pyi` stub files for the Python extension module

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#747]
# What

Investigate how to create [`.pyi`](https://peps.python.org/pep-0484/#stub-files) stub files for the `_openassetio` Python extension module and distribute them with the wheel.

Log issue(s) for steps required to integrate into our build/CI infrastructure.

# Why

Some IDEs are unable to parse binary extension modules to provide autocompletion, and even IDEs that can are rather imperfect.  

For example, PyCharm can parse binary extension modules and attempts to deduce the signature of methods from their `__doc__`, but the method signature kindly generated by pybind11 and placed in the `__doc__` is not always parsed correctly by PyCharm. 

As a specifc instance, the signature of `ManagerInteface.managementPolicy` is parsed by PyCharm as 

```
managementPolicy(self, traitSet, Set=None, p_str=None, *args, **kwargs)
```
when the `__doc__` generated by pybind11 is 
```
managementPolicy(self: openassetio._openassetio.managerApi.ManagerInterface, traitSet: List[Set[str]], context: openassetio._openassetio.Context, hostSession: openassetio._openassetio.managerApi.HostSession)
```

**Comment by feltech** [comment]
[pybind11-stubgen](https://github.com/sizmailov/pybind11-stubgen) may be of some use here.

**Comment by antirotor** [comment]
is it better to have stubs as separate package, or to have them as a part of the main one? There is some flexibility having in separate repository, but the trade-off is that you need to manage versions of two packages instead of one (but nowdays, noone is doing it manually, I hope - so that shouldn't be that much of trouble)

**Comment by JeanChristopheMorinPerso** [comment]
It's preferable to have it in the same package.

**Comment by antirotor** [comment]
I am wondering if it would be good first step to use GH actions with `pybind11-subgen` - my tests shows that it give some reasonable results and it could ensure that stubs are always up-to-date with the code, at least until it stabilize enough or there is some need to edit stubs manually.

**Comment by foundrytom** [comment]
If you had any time to look into this @antirotor that would be amazing 🙏 I guess ultimately we'd want to invoke it from CMake in the main project so that we have the `.pyi`s available during local dev work, and for emergencies if we need to do manual releases.

**Comment by feltech** [comment]
`pybind11-stubgen` works really well.  

Without stubs, PyCharm tries its best

![Image](https://github.com/OpenAssetIO/OpenAssetIO/assets/7827094/ba94225a-7bd0-42a5-903c-8e642a5a6fb3)

With stubs, the install tree looks like the following, where the `_openassetio` directory is generated:

![Image](https://github.com/OpenAssetIO/OpenAssetIO/assets/7827094/03cd73b9-3e6c-471b-a073-8b61cdb7b030)

Then autocomplete becomes instantly better

![Image](https://github.com/OpenAssetIO/OpenAssetIO/assets/7827094/ed4d978e-5ca8-4c3a-8caa-c4c6e7344e25)

So I think pybind11-stubgen is quick win. It's output is rather dense - we can tidy up with Black, if we think humans will read through the stubs.

The main question to me is how to integrate it into our build system.  pybind11-stubgen requires the Python extension module to be importable.  So generating stubs in `setup.py` might be tricky.  Yet surely we want from-source `pip install .` commands to also install the stubs.  

We can ship the stubs with the git repo, but we tend to shy away from committing generated files, for good reason...

**Comment by feltech** [comment]
There is also the more general-purpose (not tailored for pybind11) [mypy.stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html).  

The pybind11-stubgen maintainer initially wanted to [contribute to mypy and deprecate pybind11-subgen](https://github.com/sizmailov/pybind11-stubgen/issues/31), but had some issues so  "pybind11-stubgen and mypy.stubgen would co-exist for quite a while".

**Comment by feltech** [comment]
Additing the following snippet to the end of our `build_extension` method in `setup.py` results in stubs being generated and installed with a `pip install .`
```python
        stub_env = os.environ.copy()
        stub_env["PYTHONPATH"] = os.pathsep.join(
            (os.path.abspath(self.build_lib), stub_env["PYTHONPATH"])
        )
        subprocess.check_call(
            [
                "pybind11-stubgen",
                "-o",
                os.path.abspath(self.build_lib),
                "openassetio._openassetio",
            ],
            env=stub_env,
        )
```

However, `pip install --editable` doesn't install the stub files.

**Comment by feltech** [comment]
To make `--editable` installs work we must copy the generated files into the source tree (i.e. into `src/openassetio-python/package`). This is done for the `_openassetio` extension module by setuptools automatically.

We can override the `copy_extensions_to_source` method in our `build_ext` subclass to copy the `.pyi` stubs, before delegating to the base class to copy the `_openassetio` extension module itself.
```python
    def copy_extensions_to_source(self):
        build_py = self.get_finalized_command("build_py")
        self.copy_tree(
            os.path.join(self.build_lib, "openassetio", "_openassetio"),
            os.path.join(build_py.get_package_dir("openassetio"), "_openassetio"),
            level=self.verbose,
        )

        super().copy_extensions_to_source()
```

**Comment by feltech** [comment]
Closing in favour of actual implementation in #1252, as we have a way forward.
