### ISSUE TITLE
[Lint] `pylint` does not check tests due to fatal error

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#807]
## What

`pylint` aborts with a fatal error when checking the `tests ` directory due to missing `__init__.py`.  This is reproducible locally.  

This does not fail the CI run. 

Linter errors in the main sources still get reported and will fail the CI run. 

Adding the missing `__init__.py` and re-running reveals many linter errors (mostly stuff we just forgot to explicitly ignore).

From [a recent CI run](https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/4055787830/jobs/6979402597)
```
/opt/hostedtoolcache/Python/3.9.16/x64/bin/pylint --disable=fixme --ignore-paths=src/openassetio-python/tests/package/pluginSystem/resources/symlinkPath --rcfile=src/openassetio-python/pyproject.toml --output-format=json src/openassetio-python/package/openassetio src/openassetio-python/tests/package
[
    {
        "type": "fatal",
        "module": "package",
        "obj": "",
        "line": 1,
        "column": 0,
        "endLine": null,
        "endColumn": null,
        "path": "src/openassetio-python/tests/package/__init__.py",
        "symbol": "parse-error",
        "message": "error while code parsing: Unable to load file src/openassetio-python/tests/package/__init__.py:\n[Errno 2] No such file or directory: 'src/openassetio-python/tests/package/__init__.py'",
        "message-id": "F0010"
    }
]
```

**Comment by feltech** [comment]
This may be something we need to fix in `fn-pylint-action`.

**Comment by feltech** [comment]
Possible workaround: https://stackoverflow.com/a/54963445/535103

**Comment by foundrytom** [comment]
Also, `fn-pylint-action` doesn't fail if pylint is not installed :roll_eyes:
