### ISSUE TITLE
`HostSession::logger` should return a const reference

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#814]
## What

Fix the `HostSession::logger` member function to return a const reference to its logger `shared_ptr`, rather than a copy. 

## Why

Returning a const ref avoids unnecessary copies when not required. E.g. `hostSession->logger()->warning("something")` currently necessitates a copy of the `LoggerInterfacePtr`.

## Acceptance Criteria

* `&hostSession.logger() == &hostSession.logger()`

**Comment by foundrytom** [comment]
@feltech do you mean a cost-ref to the shared ptr, or the logger itself?

**Comment by feltech** [comment]
> @feltech do you mean a const-ref to the shared ptr, or the logger itself?

Const ref to the shared_ptr.  If the caller wants a copy, then `LoggerInterfacePtr logger = hostSession->logger()` will still work.  But if they don't want a copy, then `const LoggerInterfacePtr& logger = hostSession->logger()` will also work.

**Comment by foundrytom** [comment]
> > @feltech do you mean a const-ref to the shared ptr, or the logger itself?
> 
> Const ref to the shared_ptr. If the caller wants a copy, then `LoggerInterfacePtr logger = hostSession->logger()` will still work. But if they don't want a copy, then `const LoggerInterfacePtr& logger = hostSession->logger()` will also work.

Perfect, thanks, I might just update the main description to be clear its not a ref to the logger itself.
