### ISSUE TITLE
[CI] Enable TraitGen CMake CTest tests

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#841]
## What

Enable TraitGen CTest integration tests.

## Why

Since https://github.com/OpenAssetIO/OpenAssetIO-TraitGen/issues/11 (also see follow-up https://github.com/OpenAssetIO/OpenAssetIO-TraitGen/issues/17) there are C++ specific tests for TraitGen.  

We currently run the TraitGen tests alongside other Python-only tests that use OpenAssetIO installed as a Python `pip` package, which the TraitGen CMake CTest project cannot use to build against.

Currently the tests are skipped, since we don't set the `OPENASSETIO_TRAITGENTEST_CMAKE_PRESET` environment variable.  Also see #840.

## Acceptance Criteria

- TraitGen C++ test runs in `integrations.yml` (the CMake CTest tests).

## Implementation notes

We may be able to move the TraitGen test from the `python-integrations` job to the `cmake-integrations` job.

**Comment by elliotcmorris** [comment]
We were hit by this recently as some C++ changes wern't picked up during the OpenAssetIO dev, (since we only run python tests in integrations.yml) and caused an undetected break in traitgen. We should prioritize this.
