### ISSUE TITLE
[Core] Value types in batch callbacks

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#858]
## What

Consider whether `BatchElementErrorCallback` and `ResolveSuccessCallback` should take their arguments by value, rather than const ref.

## Why

Ideally we would avoid unnecessary copies in these performance-critical functions.  The most common workflow should determine whether this would be best served by a value type and possible move, rather than const ref and possible copy.

Note that `Preflight`/`RegisterSuccessCallback` take their argument (`EntityReference`) by value.

## ACs

- All batch method callbacks take their inputs by value (Ptr by value if the object is managed by a shared pointer).
- Update usage within the Core API to use best practices (eg: `std::move`).
- Update any C++ examples in-repo.

**Comment by feltech** [comment]
So

* Will the manager plugin want to re-use a `TraitsData(Ptr)` or `BatchElementError`?  This could be bad, especially if a `TraitsData` was modified after being handed off to the host as a `TraitsDataPtr`.
* Will the host want to keep hold of the TraitsData(Ptr)` or `BatchElementError` after the lifetime of the callback?

I think that the answers are "no" and "very likely", respectively - especially now that we have overloads of callback-based functions that rely on taking copies (or moves) in order to return values (as opposed to provide them to a callback).

Based on this, switching to value semantics in the callbacks seems to make sense.

**Comment by foundrytom** [comment]
Just to check, we're still talking about it it being a `TraitsDataPtr` right?

**Comment by feltech** [comment]
> Just to check, we're still talking about it it being a `TraitsDataPtr` right?

Yeah, so it's a bit misleading talking about value types, since a move of a `TraitsDataPtr` doesn't necessarily transfer ownership of the underlying `TraitsData`. But hopefully it still encourages the manager plugin authors (or rather, their linters) to consider ownership transfer.
