### ISSUE TITLE
[Core] Add equality comparison operator to BatchElementError

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#862]
## What

Add equality operator to `BatchElementError`.

## Why

This would be useful for tests, if nothing else.

## ACs

- Given two different error objects (with different addresses) `error1 == error2`
- No temp comparison implementations remain in tests/etc
- Tests that compare BEEs (🐝) updated.
- `!=` behaviour also tested if required but not if inherent in the language (C++/Python, create issue for TraitsData if were missing anything there)

## Notes

Implement as member function to follow prior art

**Comment by foundrytom** [comment]
Remember to update `ManagerTest.cpp`

**Comment by foundrytom** [comment]
... and `test_manager.py`
