### ISSUE TITLE
[Core] Use `make_shared` in `make` factory functions

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#863]
## What

In our various `make` factory functions, use `std::make_shared` rather than constructing a `std::shared_ptr` directly.

## Why

`make_shared` is best practice, not least because it co-locates `shared_ptr` metadata with the allocated type, so that an additional pointer hop is removed.

However, it's not trivial for types with a `private` constructor.  There are [a few possible workarounds](https://stackoverflow.com/questions/8147027/how-do-i-call-stdmake-shared-on-a-class-with-only-protected-or-private-const) however.

## Notes

A particular pattern (from the above linked post) that works well in our case is to have an inline `struct` that inherits from the parent and makes its constructor public, e.g.

```
ManagerPtr Manager::make(managerApi::ManagerInterfacePtr managerInterface,
                         managerApi::HostSessionPtr hostSession) {
  struct EnableMakeShared : Manager {
    EnableMakeShared(managerApi::ManagerInterfacePtr managerInterface,
                     managerApi::HostSessionPtr hostSession)
        : Manager(std::move(managerInterface), std::move(hostSession)) {}
  };

  return std::make_shared<EnableMakeShared>(std::move(managerInterface), std::move(hostSession));
}
```

**Comment by feltech** [comment]
Other possible solutions:

* `friend` a custom allocator and use `std::allocate_shared` instead of `make_shared`.  This requires copy-pasting from the STL implementation, yucky.
* Have a public move constructor, then in `create` we can use private constructor to construct on the stack, then use the public move constructor for `make_shared`.

**Comment by feltech** [comment]
Another possible solution:
* A public constructor that takes a private tag type as an argument - see https://stackoverflow.com/questions/54454620/why-cant-i-access-the-private-constructor-in-my-static-function-as-below/54456533#54456533

**Comment by foundrytom** [comment]
Closing as we previously backed-out of using this change in a real PR for readability reasons.
