### ISSUE TITLE
[Core] Make `BatchElementError` properties mutable

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#865]
## What

Following on from #864, make `BatchElementError` attributes `code` and `message` writeable.

## Why

Previously the attributes of `BatchElementError` were bound using `def_readonly`, to correspond to being `const` in the C++ implementation. However, as part of #864 we removed `const` in C++ in order to make `BatchElementError` instances copyable. This means the Python and C++ types are now inconsistent.

Note: we may decide that this is fine, since we don't _want_ users to be able to modify the attributes, it's only a language limitation that forced our hand.  Plus, the semantics of the languages re. assignment/copying are different (i.e. in Python everything is a pointer).

**Comment by elliotcmorris** [comment]
Unless and until this comes up, closing. Isn't important, works as it is ... etc.
