### ISSUE TITLE
Migrate `getWithRelationship[s]` to C++

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#913]
# What

Add `Manger` /`ManagerInterface` methods `getWithRelationship` / `getWithRelationships` to C++ and replace pure Python implementation with C++ bindings.

# Why

This is required so that C++ hosts can call these methods, and so that C++ managers can implement and override them.

# ACs

* Polymorphic methods are declared and their default implementation defined in C++ rather than Python.
* C++/Python hosts can call method implementations provided by Python/C++ manager plugins.

# Implementation notes

* Existing Python unit tests should still pass with minimal modification. Explicit C++ tests not required.
* BAL should continue to work without modification - issues added for any minor tweaks required.

**Comment by feltech** [comment]
With https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/48 now merged, I think this can be closed.
