### ISSUE TITLE
Add, and maintain a `vLatest` tag

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#917]
## What

Add a `vLatest` tag that can be used to track the latest release.

## Why

CI currently relies on manually building OpenAssetIO. If this follows `main` then it creates a discrepancy with python tests in the same project that `pip install openassetio` and inherently pick up latest on PyPi.

## ACs

- Ideally this would not be a manual process.

**Comment by feltech** [comment]
We're solving this problem by relying on pre-built release artifacts, rather than rebuilding OpenAssetIO every time.
