### ISSUE TITLE
Provide generically accesible pointer type on classes

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#918]
## What
Several of our types have their own pointer types, defined by the macro `OPENASSETIO_DECLARE_PTR`, which creates aliased shared_ptr types for that specific class, which are used heavily in their interfaces.

```cpp
#define OPENASSETIO_DECLARE_PTR(Class)             \
  /* NOLINTNEXTLINE(bugprone-macro-parentheses) */ \
  class Class;                                     \
  using Class##Ptr = std::shared_ptr<Class>;       \
  using Class##ConstPtr = std::shared_ptr<const Class>;
```

For example, in [Manager.hpp](https://github.com/OpenAssetIO/OpenAssetIO/blob/6c6690d854c4261fa3a72cc48848d8d94cdbf19f/src/openassetio-core/include/openassetio/hostApi/Manager.hpp#L32) you can see how we create a `ManagerPtr` and `ManagerConstPtr` via this macro.

We should create a alias on the type that allows us to reference the pointer type in a compile time context when we only have the main type. ie, `Manager::PtrType` (name not final) should resolve to `ManagerPtr`

## Why
This is useful in generic programming, as generic functions can be written that accept the primary type, and work freely with interfaces that accept and receive the `Ptr` types. This came up recently with regard to writing converters to/from python types, which want to apply broadly generic code across the entire api surface.

## Sketch
A possible implementation may be : 
```
OPENASSETIO_DECLARE_PTR(Manager)     

class Manager {
public:
...
using PtrType = ManagerPtr;
...
```

and a usage, taken from WIP python converters. This allows us the option to define the frontend interface as requiring either `Manager` or `ManagerPtr`, depending on our preference.
```cpp
template <typename T>
T::Ptr_Type castFromPyObject(PyObject* theObject) {
  // get Python object.
  const auto pyInstance = py::reinterpret_borrow<py::object>(theObject);

  // Extract the underlying C++ base class pointer.
  auto* cppInstancePtr = py::cast<T*>(pyInstance);

  // Use aliasing constructor, linking Python instance and C++ instance
  // lifetimes via PyObject refcount.
  return pointers::createPyRetainingPtr<T::Ptr_Type>(pyInstance, cppInstancePtr);
}
```

## Acceptance Criteria
- Generic ptr type mechanism added to all types that have pointer type declarations

**Comment by foundrytom** [comment]
Fwiw, when I've seen this done before, its been `Class::Ptr` (rather than `Ptr_Type`) as it can also be used interchangeably with `ClassPtr`.
