### ISSUE TITLE
Python exception translation

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#947]
## What

Ensure information is not lost from Python exceptions when bridged to C++

Also see #866 (duplicate issue)

## Why

We currently lose information about Python exceptions when caught in C++.

When Python code calls a C++ function, and that C++ function raises an exception, there is a built-in hook via pybind11 to translate the C++ exception to a Python exception (see usages of `register_exception_translator`).

However, when C++ calls a Python function, and that Python function raises an exception, pybind11 will detect the Python exception and throw an (unhelpfully named) `error_already_set` exception. There is no pybind11 hook available to modify this. 

In this case, consumers (hosts or manager plugins) must catch `std::exception` and interrogate the `what()` string to disambiguate.

We really need to devise a way to translate Python exceptions to the appropriate C++ exceptions, so that consumers can disambiguate using the exception type (i.e. in `catch` blocks).

An unfortunate wrinkle is in the special status that pybind11's `error_already_set` exception has within pybind11 itself. If this exception propagates _back_ into Python, then the original Python exception is restored, complete with stack trace etc.

So ideally we would only conditionally translate an `error_already_set` exception into a more appropriate C++ exception, by somehow figuring out whether the exception will be caught in C++ or Python code.

## ACs 

- Define approach for the above

**Comment by feltech** [comment]
I'd imagine any pybind11 trampoline class (i.e. anywhere we have a Python class that can inherit from C++) needs to have its member functions wrapped in `try`/`catch`, plus any other functions where we call out to Python (e.g. `createPythonPluginSystemManagerImplementationFactory`)

I wonder if multiple inheritance could help us here.

```
class openassetio::PluginError : std::runtime_error { ... };

class openassetio::PyPluginError : openassetio::PluginError, py::error_already_set { ... };

void rethrowCppException(std::exception_ptr pexc) {
  try {
    std::rethrow_exception(std::move(pexc))
  } catch (py::error_already_set& exc) {
    // ... disambiguate ... then:
   throw PyPluginError{exc};  // Absorb `error_already_set` and construct `PluginError`.
  }
}

void initialize(InfoDictionary managerSettings, const HostSessionPtr& hostSession) override {
  try {
    PYBIND11_OVERRIDE_PURE(void, ManagerInterface, initialize, std::move(managerSettings),
                           hostSession);
  } catch (...) {
    rethrowCppException(std::current_exception());
  }
}
```
Then C++ consumers can catch `PluginError` just fine, and Python consumers will have the original Python exception restored since `PyPluginError` is an `error_already_set`.  This should also work with catching in C++ then rethrowing back to Python.

**Comment by foundrytom** [comment]
Dont know if its relevant, but some prior art here too https://github.com/ImageEngine/cortex/blob/main/include/IECorePython/ExceptionAlgo.h

**Comment by feltech** [comment]
This issue duplicates #866

**Comment by feltech** [comment]
Looking specifically at the project linked above, ImageEngine's Cortex:

(Boost.Python) `error_already_set` catches are found around most of the Boost equivalent of pybind11's trampoline methods, translated to either a generic exception or using an `exception_ptr` stashed on the Python exception object.

**Comment by feltech** [comment]
Quick [Compiler Explorer mockup](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAJxmpK4AMngMmAByPgBGmMQgZtIADqgKhE4MHt6%2BAUGp6Y4CYRHRLHEJSbaY9kUMQgRMxATZPn6B1bWZDU0EJVGx8YnSCo3Nrbkdo739ZRXDAJS2qF7EyOwc5gDM4cjeWADUJltuTqPEmKzH2CYaAILbu/uYRyejWKrryQTXtw/35y8DgO8WIJAA%2BmILkx0ABPcFKAgHEAHd4gEDELyCPBscGgkhHADsVnuBzJBy86SMqII6HRmOxuPxCQxWMcTOIYOIxxJD0JABEeX8/oDgW5kslsJ9MN9MsiaXTWYzMHjOQSTMS/uSKVTgAr6WycSrmQblaquUL7hrBVteSKCJjgcpYeLJdLZQJ5a6pV86qQQWriJDaNC4QjMEiNbztc7ve66hBmcHQ/DEQdkrCfQstdrySik1DLmHEVG0SAWKgAG6YCAZrPW/1x32ZKN1z4AOgA7ggmAQINmBUSrALhSPbcL7uEkSwmOF%2B0Oc2SHbCF6Tc0viCuo4v1%2BTl6u7ruj/qUCtIydjm4jmYzAAVBBgzvhPWYeNyqhglgHZ0EBACEwAKxuAw5hmJah7Huuv6PgGXLJkWqYRtuN4KKgbCwSQoHWuBkFktaByiAQyAIAciaBvBMKIUir7IAsB64bmZZoF455uJe15mD%2Bf4MCCb6eqIXjAAgSKGOgBwOoYCgGAQmBiUQBwILCMTEHgYk0TKdQoqBrxsScvHIF2PZ9nRl7sVhQEgTeOEMXuD6oJ234uhKPoaZkEBlhW1aJp8CzZuOa6QdhAW5vhhHEaRaAMKMBxNq5/5mAAbPpJmasFR5MWeOlmTebGWNY%2BlxTxAlCSJDBiRc0H2X4HFZXpNGGb286mXp5nAVh/kQZBlWdtZ65BZ1RL8gRvbhRAkXRQWIYIeGPyJcl9G7hlLG1VeoFcZ66kekVTCCcJBwpuJqDpmCyRMMAvYvDETDIAA1gcU5Het1Xac1V71d2jUmReLVWRZ7XRuS/XWhwSy0JwAG8H4HBaKQqCcLlViWKiKxrC82w8KQBCaCDSw3SAAEJe2CVmAAHISGhcAB/iSABWxbBoWz6JwkiQ9jsOcLwCggBomPY0scCwDAiCniwyR0PE5CUGgoviwkwDU6QWCVng6wAGp4JgnYAPLJIwnAYzQtAycQXMQDEbMxOETSwvrvCW8wm5azE2iYA4tukNLbCCFrDC0Db0O8FgMSCW4Yi0Fz3CB5gM5GOIAeK3gFwOHg1YRzDr6uyxGww1ONRs7QeDKdbHhYGzDo4nzfAGMACjq5rOt65HMiCCIYjsFIzfyEoahs7oXD6IYxjWNY%2BiF1zkBLKgW0RwAtFrCgHDP7zHPyph5ZYXCErwVagqpmDj/2nSu5piZlRMfj96E4QDOUQz9wUGQCOfegP3UsyDAk/d2Mf3RjC0nhtD0N/ZOAgejNHfrfT%2Btg/7Py/n/CB8wuBLFQqsdYEhQbg1ZvHOGHADiqBJglGeCVJAHGAMgZABx/DthIRAXAhB1RmC2Eg3gWMA6%2BVIAgIsQxD540kGYImUhJCSApoSQkXB/AaH8B3MGHAWakBYPjHmUMYY4M5tzXmbDSAC2FmeZILFJaJnwEQFSdJ%2B78BbqIcQHdzFdxUOoeOfdSCdmIEwZItsMEcAhqQZR29OBaxYnopEqAqB4IIUQkhZCKFUJoR4GW9BiDXiYQsFhfMlicJhNwjxciFEASUWzVRth1GsK0Ow3hWx2xbDEWYfwJNhEAUkAlBK/hCRMw4FsLBKiOYaJKR4swHTfEcBSWwpY1YTaZBAJIIAA) of the sketch I did above, seems to be viable.
