### ISSUE TITLE
Example Manager plugin(s)

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#96]
## What

As a developer working with OpenAssetIO I need a sample implementation(s) of the `ManagerInterface` that can be used via the `PluginSystemManagerFactory`. They need to demonstrate canonical behaviour expected from a manager.

## Why

- As a host developer:
  - I need a working asset management system to perform testing of my implementation of OpenAssetIO.
  - I need a working asset management system for UX and feature design exploration.
- As an asset management system developer, I need a reference implementation to help me better understand expected behaviour or best-practice implementation patterns.
- As a developer on the OpenAssetIO team I need to be able to write working example host code.
 
## Acceptance Criteria

- [x] #131
- [ ] OpenAssetIO example code updated to work using this plugin.
- [ ] The manager(s) implement canonical behaviour based on the OpenAssetIO API contracts for:
  - [ ] A 'librarian', that isn't capable of resolving/querying future references
  - [ ] A 'path manager' that can resolve and answer attribute queries for future entities.
- [ ] The manager(s) can be configured to initialise with well-known states, containing multiple entities, relationships etc.
- [ ] The implementation is suitable for use as a code reference for other developers.

**Comment by foundrytom** [comment]
This need to be done in conjunction with #95.

**Comment by elliotcmorris** [comment]
Closing due to being out of date. We have BAL now, are looking at Ayon, etc. Other tickets capture this well enough.
