### ISSUE TITLE
Rename BatchElementError

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#961]
## What
Rename BatchElementError, do not change any of its functionality or values.
## Why
BatchElementError doesn't fully capture the conceptual basis under which it is used, and is in fact actively misleading, as it makes one believe the reason for the error is related to batching, but in actual fact, this is an error used for any problems with the input data to a method.

Thus far, this hasn't really mattered because all methods are batch, and all errors were to do with a batch element, however with the addition of singular conveniences, and more recently and starkly the Paging methods, the type is showing its misnaming more and more.

## Acceptance Criteria
 - [ ] TODO, come up with name.
 - [ ] TODO Plan for all the breaking change impact.

**Comment by foundrytom** [comment]
Closing as (through off line discussion) we realized that the majority of these concerns have been mitigated by changes to the pager workflows, other refinements to the exception/error handling behavior, and being happy that surfacing the 'batch first concept' is inherently valuable.
