### ISSUE TITLE
Investigate USD / OTIO / MovieLabs schemas

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#965]
## What

Investigate the structure and technical solutions developed by the teams developing USD / OTIO / MovieLabs schemas. In particular
* Translation of any core public schemas to OpenAssetIO traits, under an appropriate namespace
* Prior art to solving the problem of schema versioning negotiation between the producer and consumer of data.

## Why

There is no point re-inventing the wheel.  The above-mentioned projects are much more mature, and have already suffered attempting to find schemas that have community consensus, and solving the technical problems around mutating schemas over time.

**Comment by elliotcmorris** [comment]
This train has somewhat sailed. We have our Mediacreation initial set of traits and specs, and any further ones we expect will come from usage/neccesity, rather than pre-emption.

**Comment by feltech** [comment]
I'll add to the above, re. MovieLabs, we do want to adopt the ontology wherever possible, but at time of writing the post-production and CG assets element is still under active discussion.
